# -*- coding: utf-8 -*-
"""TSSM_v8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TbNj9yCWW61hFX-BFsyH5nRCbXQPE4PC
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Tuple

import numpy as np
from scipy import linalg as la
import matplotlib.pyplot as plt


# ============================================================
# TQS v8.0 — TOPOLOGICAL SPECTRAL SUSCEPTIBILITY
# Standalone synthetic implementation; no internet/PDB access.
# ============================================================


@dataclass(frozen=True)
class Config:
    # ---------- Layer 1: 3D ENM ----------
    cutoff_A: float = 7.0
    spring_k: float = 1.0

    target_n: int = 100
    control_n: int = 80

    target_turns: float = 5.0
    control_turns: float = 4.5

    target_radius_A: float = 8.0
    control_radius_A: float = 8.0

    target_pitch_A_per_rad: float = 0.25
    control_pitch_A_per_rad: float = 0.25

    target_phase_rad: float = 0.00
    control_phase_rad: float = 0.41

    radial_modulation: float = 0.08
    axial_warp_A: float = 0.80
    axial_warp_freq: float = 0.37
    radial_warp_freq: float = 0.71

    # ---------- Layer 1: topology null ----------
    random_swaps_per_edge: int = 20
    max_swap_attempt_factor: int = 80

    # ---------- Causal ablation ----------
    top_ablation_fraction: float = 0.05
    random_ablation_runs: int = 30

    # ---------- Spectral leverage ----------
    soft_mode_count: int = 10
    mode_start_full_index: int = 6

    # ---------- Numerical tolerance ----------
    eig_abs_tol: float = 1e-10
    eig_rel_tol: float = 1e-8
    density_floor: float = 1e-12

    # ---------- Layer 2: phenomenological quantum closure ----------
    # These are closure parameters, NOT calibrated physical constants.
    gamma_floor_per_us: float = 0.02
    gamma_span_per_us: float = 0.30

    lindblad_total_time_us: float = 5.0
    lindblad_dt_us: float = 0.001

    earth_B_T: float = 5.0e-5
    electron_gyromagnetic_rad_s_T: float = 1.76085963023e11

    hyperfine_A1_MHz: float = 12.0
    hyperfine_A2_MHz: float = 4.0

    # ---------- Density representation ----------
    density_bins: int = 96

    # ---------- Reproducibility ----------
    rng_seed: int = 20260921


@dataclass(frozen=True)
class MechanicalState:
    name: str
    coords_A: np.ndarray
    edges: np.ndarray

    hessian: np.ndarray
    eigenvalues: np.ndarray
    eigenvectors: np.ndarray

    positive_eigenvalues: np.ndarray
    positive_eigenvectors: np.ndarray

    leverage: np.ndarray
    leverage_normalized: np.ndarray

    spectral_gini: float
    leverage_ipr: float
    leverage_pr: float


# ============================================================
# SYNTHETIC 3D POLYMER FOLD
# ============================================================

def generate_spiral_fold(
    n: int,
    turns: float,
    radius_A: float,
    pitch_A_per_rad: float,
    phase_rad: float,
    radial_modulation: float,
    axial_warp_A: float,
    axial_warp_freq: float,
    radial_warp_freq: float,
) -> np.ndarray:
    """
    Deterministic 3D spiral/polymer-like fold.

    This is deliberately synthetic:
    it replaces PDB I/O so the experiment is standalone and reproducible.
    """
    t = np.linspace(
        0.0,
        turns * 2.0 * np.pi,
        n,
        dtype=float,
    )

    r = radius_A * (
        1.0
        + radial_modulation
        * np.sin(radial_warp_freq * t + phase_rad)
    )

    x = r * np.cos(t + phase_rad)
    y = r * np.sin(t + phase_rad)

    z = (
        pitch_A_per_rad * t
        + axial_warp_A
        * np.sin(axial_warp_freq * t + 0.3 * phase_rad)
    )

    coords = np.column_stack((x, y, z))

    # Remove global translation only.
    coords -= coords.mean(axis=0, keepdims=True)

    return coords


# ============================================================
# CONTACT GRAPH
# ============================================================

def contact_graph(
    coords_A: np.ndarray,
    cutoff_A: float,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Strict spatial contact rule:
        ||r_i-r_j|| <= cutoff_A
    """
    diff = coords_A[:, None, :] - coords_A[None, :, :]
    dist2 = np.einsum("ijk,ijk->ij", diff, diff)

    upper_i, upper_j = np.triu_indices(
        coords_A.shape[0],
        k=1,
    )

    mask = dist2[upper_i, upper_j] <= cutoff_A * cutoff_A

    edges = np.column_stack(
        (upper_i[mask], upper_j[mask])
    ).astype(int, copy=False)

    distances = np.sqrt(
        dist2[upper_i[mask], upper_j[mask]]
    )

    adjacency = np.zeros(
        (coords_A.shape[0], coords_A.shape[0]),
        dtype=bool,
    )

    adjacency[
        edges[:, 0],
        edges[:, 1]
    ] = True

    adjacency[
        edges[:, 1],
        edges[:, 0]
    ] = True

    return edges, distances, adjacency


def degree_sequence(
    edges: np.ndarray,
    n: int,
) -> np.ndarray:
    deg = np.bincount(
        edges.reshape(-1),
        minlength=n,
    )

    return deg.astype(
        int,
        copy=False,
    )


# ============================================================
# DEGREE-PRESERVING MASLOV–SNEPPEN NULL
# ============================================================

def degree_preserving_maslov_sneppen(
    edges: np.ndarray,
    n: int,
    swaps_per_edge: int,
    max_attempt_factor: int,
    rng: np.random.Generator,
) -> Tuple[np.ndarray, int, int]:
    """
    Topology-only null ensemble.

    Important:
    - degree sequence is preserved exactly
    - edge count is preserved exactly
    - node labels are preserved
    - spatial geometry is NOT used as an acceptance constraint

    Thus the null intentionally destroys native spatial contact organization.
    This is a topology-null, not a physically realistic protein conformation.
    """

    if edges.size == 0:
        raise ValueError("Cannot randomize an empty graph.")

    edge_list = [
        tuple(map(int, e))
        for e in edges
    ]

    edge_set = set(edge_list)

    def canonical(a: int, b: int) -> Tuple[int, int]:
        return (a, b) if a < b else (b, a)

    target_accepts = max(
        swaps_per_edge * len(edge_list),
        20,
    )

    max_attempts = max(
        target_accepts * max_attempt_factor,
        10000,
    )

    accepted = 0
    attempts = 0

    while (
        accepted < target_accepts
        and attempts < max_attempts
    ):
        attempts += 1

        e1_idx, e2_idx = rng.choice(
            len(edge_list),
            size=2,
            replace=False,
        )

        a, b = edge_list[e1_idx]
        c, d = edge_list[e2_idx]

        # Standard double-edge swap requires 4 distinct nodes.
        if len({a, b, c, d}) < 4:
            continue

        if rng.random() < 0.5:
            new1 = canonical(a, d)
            new2 = canonical(c, b)
        else:
            new1 = canonical(a, c)
            new2 = canonical(b, d)

        # No self loops.
        if (
            new1[0] == new1[1]
            or new2[0] == new2[1]
        ):
            continue

        # No duplicate edges.
        if (
            new1 in edge_set
            or new2 in edge_set
        ):
            continue

        old1 = canonical(a, b)
        old2 = canonical(c, d)

        edge_set.remove(old1)
        edge_set.remove(old2)

        edge_set.add(new1)
        edge_set.add(new2)

        edge_list[e1_idx] = new1
        edge_list[e2_idx] = new2

        accepted += 1

    if accepted < target_accepts:
        raise RuntimeError(
            "Maslov-Sneppen rewiring stalled: "
            f"accepted={accepted}, "
            f"target={target_accepts}, "
            f"attempts={attempts}"
        )

    randomized = np.array(
        sorted(edge_set),
        dtype=int,
    )

    if randomized.shape != edges.shape:
        raise RuntimeError(
            "Degree-preserving rewiring changed edge count."
        )

    # Sanity-check node bounds.
    if (
        np.min(randomized) < 0
        or np.max(randomized) >= n
    ):
        raise RuntimeError(
            "Randomized graph contains an invalid node index."
        )

    return randomized, accepted, attempts


# ============================================================
# 3D ENM HESSIAN
# ============================================================

def build_enm_hessian(
    coords_A: np.ndarray,
    edges: np.ndarray,
    spring_k: float,
) -> np.ndarray:
    """
    Central-force 3D ENM/ANM-type Hessian:

        H_ii += k P_ij
        H_jj += k P_ij
        H_ij -= k P_ij
        H_ji -= k P_ij

    where
        P_ij = u_ij u_ij^T
    """

    n = coords_A.shape[0]
    dim = 3 * n

    h = np.zeros(
        (dim, dim),
        dtype=float,
    )

    ri = coords_A[edges[:, 0]]
    rj = coords_A[edges[:, 1]]

    delta = rj - ri

    norms = np.linalg.norm(
        delta,
        axis=1,
    )

    if np.any(norms <= 0.0):
        raise ValueError(
            "Zero-length edge encountered."
        )

    unit_vectors = delta / norms[:, None]

    projectors = spring_k * np.einsum(
        "ea,eb->eab",
        unit_vectors,
        unit_vectors,
    )

    local_i = (
        3 * edges[:, 0, None]
        + np.arange(3)[None, :]
    )

    local_j = (
        3 * edges[:, 1, None]
        + np.arange(3)[None, :]
    )

    ii_rows = np.broadcast_to(
        local_i[:, :, None],
        projectors.shape,
    )

    ii_cols = np.broadcast_to(
        local_i[:, None, :],
        projectors.shape,
    )

    jj_rows = np.broadcast_to(
        local_j[:, :, None],
        projectors.shape,
    )

    jj_cols = np.broadcast_to(
        local_j[:, None, :],
        projectors.shape,
    )

    np.add.at(
        h,
        (
            ii_rows.ravel(),
            ii_cols.ravel(),
        ),
        projectors.ravel(),
    )

    np.add.at(
        h,
        (
            jj_rows.ravel(),
            jj_cols.ravel(),
        ),
        projectors.ravel(),
    )

    np.add.at(
        h,
        (
            ii_rows.ravel(),
            jj_cols.ravel(),
        ),
        -projectors.ravel(),
    )

    np.add.at(
        h,
        (
            jj_rows.ravel(),
            ii_cols.ravel(),
        ),
        -projectors.ravel(),
    )

    # Numerical symmetrization only.
    h = 0.5 * (h + h.T)

    return h


# ============================================================
# EIGENVALUE DIAGONALIZATION / RIGID-BODY SCRUB
# ============================================================

def rigid_body_zero_tolerance(
    eigenvalues: np.ndarray,
    cfg: Config,
) -> float:
    scale = max(
        1.0,
        float(np.max(np.abs(eigenvalues))),
    )

    return max(
        cfg.eig_abs_tol,
        cfg.eig_rel_tol * scale,
    )


def diagonalize_and_scrub(
    hessian: np.ndarray,
    cfg: Config,
) -> Tuple[
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    float,
]:
    """
    Full symmetric eigendecomposition:
        H v_k = lambda_k v_k

    Expected central-force rigid-body nullspace:
        3 translations + 3 rotations = 6 modes.
    """

    eigenvalues, eigenvectors = la.eigh(
        hessian,
        check_finite=True,
        overwrite_a=False,
    )

    tol = rigid_body_zero_tolerance(
        eigenvalues,
        cfg,
    )

    # ENM central-force Hessian should be PSD up to roundoff.
    min_eval = float(np.min(eigenvalues))

    if min_eval < -10.0 * tol:
        raise RuntimeError(
            "Hessian is not positive-semidefinite "
            f"within tolerance: min={min_eval:.3e}"
        )

    required_modes = (
        cfg.mode_start_full_index
        + cfg.soft_mode_count
        + 1
    )

    if eigenvalues.shape[0] < required_modes:
        raise RuntimeError(
            "Matrix is too small for requested soft-mode window."
        )

    # Explicit six-mode rigid-body check.
    rigid = eigenvalues[
        :cfg.mode_start_full_index
    ]

    if not np.all(
        np.abs(rigid) <= 10.0 * tol
    ):
        raise RuntimeError(
            "Expected six rigid-body modes at "
            "the bottom of the spectrum, but found:\n"
            f"{rigid}"
        )

    positive_mask = eigenvalues > tol

    positive_eigenvalues = eigenvalues[
        positive_mask
    ]

    positive_eigenvectors = eigenvectors[
        :,
        positive_mask
    ]

    if (
        positive_eigenvalues.size
        < cfg.soft_mode_count
    ):
        raise RuntimeError(
            "Insufficient positive modes after "
            "rigid-body scrubbing."
        )

    return (
        eigenvalues,
        eigenvectors,
        positive_eigenvalues,
        positive_eigenvectors,
        tol,
    )


# ============================================================
# FIRST-PRINCIPLES EDGE SPECTRAL SENSITIVITY
# ============================================================

def edge_spectral_leverage(
    coords_A: np.ndarray,
    edges: np.ndarray,
    positive_vectors: np.ndarray,
    positive_values: np.ndarray,
    cfg: Config,
) -> np.ndarray:
    """
    Rayleigh first-order eigenvalue sensitivity:

      d lambda_k / d w_ij
      =
      (v_i - v_j)^T P_ij (v_i - v_j)

    Since
        P_ij = u_ij u_ij^T,

    this becomes

      S_{e,k}
      =
      [u_ij^T (v_i-v_j)]^2.

    Global edge leverage:

      L_e = sum_k alpha_k S_{e,k}

    with
      alpha_k ∝ 1/lambda_k
    over the ten lowest positive modes.
    """

    k_count = min(
        cfg.soft_mode_count,
        positive_values.size,
    )

    # (3N, K) -> (N, 3, K)
    mode_vectors = positive_vectors[
        :, :k_count
    ].reshape(
        coords_A.shape[0],
        3,
        k_count,
    )

    vi = mode_vectors[
        edges[:, 0]
    ]

    vj = mode_vectors[
        edges[:, 1]
    ]

    delta_modes = vi - vj

    ri = coords_A[
        edges[:, 0]
    ]

    rj = coords_A[
        edges[:, 1]
    ]

    unit_vectors = rj - ri
    unit_vectors /= np.linalg.norm(
        unit_vectors,
        axis=1,
        keepdims=True,
    )

    # E x K
    projected = np.einsum(
        "ea,eak->ek",
        unit_vectors,
        delta_modes,
    )

    sensitivities = projected * projected

    # alpha_k ∝ 1/lambda_k
    alpha = 1.0 / np.maximum(
        positive_values[:k_count],
        cfg.density_floor,
    )

    alpha /= np.sum(alpha)

    # E
    leverage = sensitivities @ alpha

    if np.any(
        leverage < -cfg.eig_abs_tol
    ):
        raise RuntimeError(
            "Spectral leverage became negative."
        )

    return np.maximum(
        leverage,
        0.0,
    )


# ============================================================
# LEVERAGE DISTRIBUTION METRICS
# ============================================================

def spectral_gini(
    values: np.ndarray,
) -> float:
    """
    Gini coefficient for a nonnegative vector.
    """

    x = np.asarray(
        values,
        dtype=float,
    )

    if (
        x.size == 0
        or np.any(x < 0.0)
    ):
        raise ValueError(
            "Gini input must be nonempty and nonnegative."
        )

    total = float(
        np.sum(x)
    )

    if total <= 0.0:
        return 0.0

    x = np.sort(x)

    n = x.size
    rank = np.arange(
        1,
        n + 1,
        dtype=float,
    )

    return float(
        (
            2.0 * np.sum(rank * x)
            - (n + 1.0) * np.sum(x)
        )
        / (n * total)
    )


def leverage_metrics(
    leverage: np.ndarray,
) -> Tuple[
    float,
    np.ndarray,
    float,
    float,
]:
    total = float(
        np.sum(leverage)
    )

    if total <= 0.0:
        raise ValueError(
            "Leverage vector has zero total mass."
        )

    p = leverage / total

    # Edge-distribution IPR:
        # IPR_L = sum_e p_e^2
    ipr = float(
        np.sum(p * p)
    )

    # Effective edge participation ratio.
    pr = float(
        1.0 / ipr
    )

    gini = spectral_gini(
        leverage
    )

    return (
        gini,
        p,
        ipr,
        pr,
    )


# ============================================================
# MECHANICAL STATE CONSTRUCTION
# ============================================================

def make_mechanical_state(
    name: str,
    coords_A: np.ndarray,
    edges: np.ndarray,
    cfg: Config,
) -> MechanicalState:

    hessian = build_enm_hessian(
        coords_A,
        edges,
        cfg.spring_k,
    )

    (
        eigenvalues,
        eigenvectors,
        positive_eigenvalues,
        positive_eigenvectors,
        _tol,
    ) = diagonalize_and_scrub(
        hessian,
        cfg,
    )

    leverage = edge_spectral_leverage(
        coords_A,
        edges,
        positive_eigenvectors,
        positive_eigenvalues,
        cfg,
    )

    (
        gini,
        leverage_normalized,
        ipr,
        pr,
    ) = leverage_metrics(
        leverage
    )

    return MechanicalState(
        name=name,
        coords_A=coords_A,
        edges=edges,
        hessian=hessian,
        eigenvalues=eigenvalues,
        eigenvectors=eigenvectors,
        positive_eigenvalues=positive_eigenvalues,
        positive_eigenvectors=positive_eigenvectors,
        leverage=leverage,
        leverage_normalized=leverage_normalized,
        spectral_gini=gini,
        leverage_ipr=ipr,
        leverage_pr=pr,
    )


# ============================================================
# ABLATION
# ============================================================

def ablate_edges(
    edges: np.ndarray,
    removed_indices: np.ndarray,
) -> np.ndarray:
    mask = np.ones(
        edges.shape[0],
        dtype=bool,
    )

    mask[
        np.asarray(
            removed_indices,
            dtype=int,
        )
    ] = False

    ablated = edges[mask]

    if ablated.shape[0] == 0:
        raise RuntimeError(
            "Ablation removed all edges."
        )

    return ablated


def smallest_positive_eigenvalue(
    hessian: np.ndarray,
    cfg: Config,
) -> float:

    eigenvalues = la.eigvalsh(
        hessian,
        check_finite=True,
        overwrite_a=False,
    )

    tol = rigid_body_zero_tolerance(
        eigenvalues,
        cfg,
    )

    positive = eigenvalues[
        eigenvalues > tol
    ]

    if positive.size == 0:
        return float("nan")

    return float(
        positive[0]
    )


def top_leverage_ablation(
    state: MechanicalState,
    fraction: float,
    cfg: Config,
) -> Tuple[
    np.ndarray,
    np.ndarray,
    float,
    float,
]:

    m = state.edges.shape[0]

    remove_n = max(
        1,
        int(np.ceil(
            fraction * m
        )),
    )

    order = np.argsort(
        state.leverage
    )[::-1]

    remove_indices = order[
        :remove_n
    ]

    ablated_edges = ablate_edges(
        state.edges,
        remove_indices,
    )

    ablated_hessian = build_enm_hessian(
        state.coords_A,
        ablated_edges,
        cfg.spring_k,
    )

    lambda_native = (
        smallest_positive_eigenvalue(
            state.hessian,
            cfg,
        )
    )

    lambda_ablated = (
        smallest_positive_eigenvalue(
            ablated_hessian,
            cfg,
        )
    )

    delta_lambda = (
        lambda_ablated
        - lambda_native
    )

    return (
        ablated_edges,
        remove_indices,
        delta_lambda,
        lambda_ablated,
    )


def random_ablation_ensemble(
    state: MechanicalState,
    fraction: float,
    runs: int,
    rng: np.random.Generator,
    cfg: Config,
) -> np.ndarray:

    m = state.edges.shape[0]

    remove_n = max(
        1,
        int(np.ceil(
            fraction * m
        )),
    )

    lambda_native = (
        smallest_positive_eigenvalue(
            state.hessian,
            cfg,
        )
    )

    deltas = np.empty(
        runs,
        dtype=float,
    )

    for run in range(runs):

        remove_indices = rng.choice(
            m,
            size=remove_n,
            replace=False,
        )

        random_edges = ablate_edges(
            state.edges,
            remove_indices,
        )

        random_hessian = build_enm_hessian(
            state.coords_A,
            random_edges,
            cfg.spring_k,
        )

        lambda_random = (
            smallest_positive_eigenvalue(
                random_hessian,
                cfg,
            )
        )

        deltas[run] = (
            lambda_random
            - lambda_native
        )

    return deltas


def empirical_two_sided_p(
    value: float,
    null_values: np.ndarray,
) -> float:
    """
    Randomization-test p-value.
    """

    extreme = np.count_nonzero(
        np.abs(null_values)
        >= abs(value)
    )

    return float(
        (1 + extreme)
        / (null_values.size + 1)
    )


# ============================================================
# LEVERAGE DENSITY + L1/TV BRIDGE
# ============================================================

def histogram_density(
    values: np.ndarray,
    bins: np.ndarray,
) -> np.ndarray:

    counts, _ = np.histogram(
        values,
        bins=bins,
        density=False,
    )

    widths = np.diff(bins)

    density = (
        counts.astype(float)
        / max(
            float(np.sum(counts)),
            1.0,
        )
        / widths
    )

    area = float(
        np.sum(
            density * widths
        )
    )

    if area <= 0.0:
        raise RuntimeError(
            "Could not normalize density."
        )

    return density / area


def total_variation_from_hist(
    p: np.ndarray,
    q: np.ndarray,
    bins: np.ndarray,
) -> float:

    widths = np.diff(
        bins
    )

    return float(
        0.5
        * np.sum(
            np.abs(p - q)
            * widths
        )
    )


def prepare_common_leverage_density(
    states: List[MechanicalState],
    cfg: Config,
) -> Tuple[
    np.ndarray,
    Dict[str, np.ndarray],
]:

    pooled = np.concatenate(
        [
            state.leverage
            for state in states
        ]
    )

    lo = float(
        np.min(pooled)
    )

    hi = float(
        np.max(pooled)
    )

    if hi <= lo:
        hi = lo + 1.0

    margin = 0.05 * (
        hi - lo
    )

    bins = np.linspace(
        max(
            0.0,
            lo - margin,
        ),
        hi + margin,
        cfg.density_bins + 1,
    )

    densities = {
        state.name:
        histogram_density(
            state.leverage,
            bins,
        )
        for state in states
    }

    return bins, densities


def gamma_from_tv(
    tv_distance: float,
    cfg: Config,
) -> float:
    """
    Monotone phenomenological closure:

        gamma_eff =
            gamma_floor
            + gamma_span * TV

    This is NOT a first-principles microscopic
    radical-pair rate law.
    """

    tv_bounded = float(
        np.clip(
            tv_distance,
            0.0,
            1.0,
        )
    )

    return (
        cfg.gamma_floor_per_us
        + cfg.gamma_span_per_us
        * tv_bounded
    )


# ============================================================
# 4x4 ELECTRON SPIN MODEL
# ============================================================

def single_spin_z() -> np.ndarray:
    return 0.5 * np.array(
        [
            [1.0, 0.0],
            [0.0, -1.0],
        ],
        dtype=complex,
    )


def identity_2() -> np.ndarray:
    return np.eye(
        2,
        dtype=complex,
    )


def singlet_triplet_basis() -> np.ndarray:
    up = np.array(
        [1.0, 0.0],
        dtype=complex,
    )

    down = np.array(
        [0.0, 1.0],
        dtype=complex,
    )

    uu = np.kron(
        up,
        up,
    )

    ud = np.kron(
        up,
        down,
    )

    du = np.kron(
        down,
        up,
    )

    dd = np.kron(
        down,
        down,
    )

    singlet = (
        ud - du
    ) / np.sqrt(2.0)

    triplet_0 = (
        ud + du
    ) / np.sqrt(2.0)

    triplet_plus = uu
    triplet_minus = dd

    # Column order:
    #   S, T+, T0, T-
    return np.column_stack(
        (
            singlet,
            triplet_plus,
            triplet_0,
            triplet_minus,
        )
    )


def build_spin_hamiltonian(
    cfg: Config,
) -> Tuple[
    np.ndarray,
    np.ndarray,
    List[np.ndarray],
]:
    """
    Standalone 4x4 electron-only closure.

    Product basis Hamiltonian:
        H =
        omega_B(S1z + S2z)
        + A1*S1z
        + A2*S2z

    It is intentionally an effective toy closure:
    no explicit nuclear Hilbert space is included.
    """

    sz = single_spin_z()
    ident = identity_2()

    s1z = np.kron(
        sz,
        ident,
    )

    s2z = np.kron(
        ident,
        sz,
    )

    omega_B = (
        cfg.electron_gyromagnetic_rad_s_T
        * cfg.earth_B_T
        * 1e-6
    )

    A1 = (
        2.0
        * np.pi
        * cfg.hyperfine_A1_MHz
    )

    A2 = (
        2.0
        * np.pi
        * cfg.hyperfine_A2_MHz
    )

    H_product = (
        omega_B
        * (s1z + s2z)
        + A1 * s1z
        + A2 * s2z
    )

    U = singlet_triplet_basis()

    H_st = (
        U.conj().T
        @ H_product
        @ U
    )

    # Singlet projector.
    P_S = np.zeros(
        (4, 4),
        dtype=complex,
    )

    P_S[0, 0] = 1.0

    # Jump channels:
    # |S> -> |T+>, |T0>, |T->
    jump_ops = []

    for triplet_index in (
        1,
        2,
        3,
    ):
        jump = np.zeros(
            (4, 4),
            dtype=complex,
        )

        jump[
            triplet_index,
            0
        ] = 1.0

        jump_ops.append(jump)

    return (
        H_st,
        P_S,
        jump_ops,
    )


# ============================================================
# LINDBLAD DYNAMICS
# ============================================================

def lindblad_rhs(
    rho: np.ndarray,
    H: np.ndarray,
    jump_ops: List[np.ndarray],
    gamma_eff: float,
) -> np.ndarray:

    commutator = (
        H @ rho
        - rho @ H
    )

    drho = -1j * commutator

    if gamma_eff > 0.0:

        for jump in jump_ops:

            jump_scaled = (
                np.sqrt(
                    gamma_eff / 3.0
                )
                * jump
            )

            jump_dag_jump = (
                jump_scaled.conj().T
                @ jump_scaled
            )

            drho += (
                jump_scaled
                @ rho
                @ jump_scaled.conj().T
                - 0.5
                * (
                    jump_dag_jump @ rho
                    + rho @ jump_dag_jump
                )
            )

    return drho


def positivity_guard(
    rho: np.ndarray,
) -> np.ndarray:
    """
    Numerical physical-state projection:

    1. Hermitize
    2. Normalize trace
    3. Diagonalize rho
    4. Clip tiny negative eigenvalues
    5. Renormalize trace

    This is a numerical safeguard, not a new
    physical term in the Lindblad generator.
    """

    rho = 0.5 * (
        rho + rho.conj().T
    )

    trace = float(
        np.real(
            np.trace(rho)
        )
    )

    if trace <= 0.0:
        raise RuntimeError(
            "Density-matrix trace became nonpositive."
        )

    rho /= trace

    values, vectors = la.eigh(
        rho,
        check_finite=True,
    )

    values = np.maximum(
        values,
        0.0,
    )

    total = float(
        np.sum(values)
    )

    if total <= 0.0:
        raise RuntimeError(
            "Positivity projection produced zero trace."
        )

    rho = (
        vectors
        * values
    ) @ vectors.conj().T

    rho = 0.5 * (
        rho + rho.conj().T
    )

    rho /= np.real(
        np.trace(rho)
    )

    return rho


def integrate_lindblad(
    gamma_eff: float,
    cfg: Config,
    H: np.ndarray,
    P_S: np.ndarray,
    jump_ops: List[np.ndarray],
) -> Tuple[
    np.ndarray,
    np.ndarray,
]:

    steps = int(
        round(
            cfg.lindblad_total_time_us
            / cfg.lindblad_dt_us
        )
    )

    if steps <= 0:
        raise ValueError(
            "Lindblad integration requires "
            "a positive number of steps."
        )

    times = np.linspace(
        0.0,
        cfg.lindblad_total_time_us,
        steps + 1,
    )

    # Initial state = pure singlet.
    rho = P_S.copy()

    Y_S = np.empty(
        steps + 1,
        dtype=float,
    )

    Y_S[0] = float(
        np.real(
            np.trace(
                P_S @ rho
            )
        )
    )

    dt = cfg.lindblad_dt_us

    for step in range(steps):

        # Explicit RK4 loop.
        k1 = lindblad_rhs(
            rho,
            H,
            jump_ops,
            gamma_eff,
        )

        k2 = lindblad_rhs(
            rho + 0.5 * dt * k1,
            H,
            jump_ops,
            gamma_eff,
        )

        k3 = lindblad_rhs(
            rho + 0.5 * dt * k2,
            H,
            jump_ops,
            gamma_eff,
        )

        k4 = lindblad_rhs(
            rho + dt * k3,
            H,
            jump_ops,
            gamma_eff,
        )

        rho = rho + (
            dt / 6.0
        ) * (
            k1
            + 2.0 * k2
            + 2.0 * k3
            + k4
        )

        # Numerical physical-state guard.
        rho = positivity_guard(
            rho
        )

        trace_error = abs(
            np.trace(rho) - 1.0
        )

        hermiticity_error = np.max(
            np.abs(
                rho - rho.conj().T
            )
        )

        min_density_eigenvalue = float(
            np.min(
                la.eigvalsh(rho)
            )
        )

        if (
            trace_error > 1e-10
            or hermiticity_error > 1e-10
            or min_density_eigenvalue < -1e-10
        ):
            raise FloatingPointError(
                "Density-matrix guard failed "
                f"at step {step}: "
                f"trace={trace_error:.3e}, "
                f"hermiticity={hermiticity_error:.3e}, "
                f"min_eig={min_density_eigenvalue:.3e}"
            )

        Y_S[step + 1] = float(
            np.real(
                np.trace(
                    P_S @ rho
                )
            )
        )

    return (
        times,
        Y_S,
    )


# ============================================================
# FACTORIAL / COMPARATIVE STATES
# ============================================================

def build_comparative_states(
    target: MechanicalState,
    target_random: MechanicalState,
    cfg: Config,
    rng: np.random.Generator,
) -> Tuple[
    MechanicalState,
    MechanicalState,
    MechanicalState,
    np.ndarray,
    Tuple[float, float, float, float],
]:

    # ---- Native top-leverage ablation ----
    (
        top_edges,
        _top_removed,
        top_delta,
        top_lambda,
    ) = top_leverage_ablation(
        target,
        cfg.top_ablation_fraction,
        cfg,
    )

    target_top = make_mechanical_state(
        "Target_top5pct_ablation",
        target.coords_A,
        top_edges,
        cfg,
    )

    # ---- Null-top-leverage ablation ----
    (
        null_top_edges,
        _null_top_removed,
        null_top_delta,
        null_top_lambda,
    ) = top_leverage_ablation(
        target_random,
        cfg.top_ablation_fraction,
        cfg,
    )

    null_top = make_mechanical_state(
        "Null_top5pct_ablation",
        target_random.coords_A,
        null_top_edges,
        cfg,
    )

    # ---- Random ablation null ensemble ----
    random_deltas = random_ablation_ensemble(
        target,
        cfg.top_ablation_fraction,
        cfg.random_ablation_runs,
        rng,
        cfg,
    )

    # Representative random-ablation trajectory:
    # use a random realization close to the median delta.
    m = target.edges.shape[0]

    remove_n = max(
        1,
        int(np.ceil(
            cfg.top_ablation_fraction * m
        )),
    )

    baseline_lambda = (
        smallest_positive_eigenvalue(
            target.hessian,
            cfg,
        )
    )

    candidates = []

    for _ in range(
        max(
            10,
            cfg.random_ablation_runs
        )
    ):

        remove_indices = rng.choice(
            m,
            size=remove_n,
            replace=False,
        )

        edges_candidate = ablate_edges(
            target.edges,
            remove_indices,
        )

        h_candidate = build_enm_hessian(
            target.coords_A,
            edges_candidate,
            cfg.spring_k,
        )

        lambda_candidate = (
            smallest_positive_eigenvalue(
                h_candidate,
                cfg,
            )
        )

        delta_candidate = (
            lambda_candidate
            - baseline_lambda
        )

        candidates.append(
            (
                delta_candidate,
                edges_candidate,
            )
        )

    median_delta = float(
        np.median(
            random_deltas
        )
    )

    candidates.sort(
        key=lambda item:
        abs(
            item[0]
            - median_delta
        )
    )

    representative_random_edges = (
        candidates[0][1]
    )

    target_random_ablation = (
        make_mechanical_state(
            "Target_random5pct_ablation",
            target.coords_A,
            representative_random_edges,
            cfg,
        )
    )

    metadata = (
        top_delta,
        top_lambda,
        null_top_delta,
        null_top_lambda,
    )

    return (
        target_top,
        null_top,
        target_random_ablation,
        random_deltas,
        metadata,
    )


# ============================================================
# DISPLAY
# ============================================================

def format_metrics(
    state: MechanicalState,
) -> str:

    return (
        f"{state.name:31s} "
        f"N={state.coords_A.shape[0]:3d} "
        f"E={state.edges.shape[0]:4d} "
        f"Gini={state.spectral_gini:8.5f} "
        f"IPR_L={state.leverage_ipr:10.6f} "
        f"PR_L={state.leverage_pr:8.2f}"
    )


# ============================================================
# MAIN
# ============================================================

def main() -> None:

    cfg = Config()

    rng = np.random.default_rng(
        cfg.rng_seed
    )

    # --------------------------------------------------------
    # 1. SYNTHETIC GEOMETRIES
    # --------------------------------------------------------

    target_coords = generate_spiral_fold(
        cfg.target_n,
        cfg.target_turns,
        cfg.target_radius_A,
        cfg.target_pitch_A_per_rad,
        cfg.target_phase_rad,
        cfg.radial_modulation,
        cfg.axial_warp_A,
        cfg.axial_warp_freq,
        cfg.radial_warp_freq,
    )

    control_coords = generate_spiral_fold(
        cfg.control_n,
        cfg.control_turns,
        cfg.control_radius_A,
        cfg.control_pitch_A_per_rad,
        cfg.control_phase_rad,
        cfg.radial_modulation,
        cfg.axial_warp_A,
        cfg.axial_warp_freq,
        cfg.radial_warp_freq,
    )

    # --------------------------------------------------------
    # 2. NATIVE CONTACT GRAPHS
    # --------------------------------------------------------

    target_edges, _, _ = contact_graph(
        target_coords,
        cfg.cutoff_A,
    )

    control_edges, _, _ = contact_graph(
        control_coords,
        cfg.cutoff_A,
    )

    if target_edges.size == 0:
        raise RuntimeError(
            "Target synthetic fold generated no contacts."
        )

    if control_edges.size == 0:
        raise RuntimeError(
            "Control synthetic fold generated no contacts."
        )

    # Native target degree sequence.
    target_degree = degree_sequence(
        target_edges,
        cfg.target_n,
    )

    # --------------------------------------------------------
    # 3. ACTUAL MASLOV–SNEPPEN NULL
    # --------------------------------------------------------

    (
        target_random_edges,
        accepted_swaps,
        swap_attempts,
    ) = degree_preserving_maslov_sneppen(
        target_edges,
        cfg.target_n,
        cfg.random_swaps_per_edge,
        cfg.max_swap_attempt_factor,
        rng,
    )

    target_random_degree = degree_sequence(
        target_random_edges,
        cfg.target_n,
    )

    # Hard invariance assertions.
    assert np.array_equal(
        target_degree,
        target_random_degree,
    ), "Degree sequence changed."

    assert (
        target_random_edges.shape
        == target_edges.shape
    ), "Edge count changed."

    # --------------------------------------------------------
    # 4. NATIVE + CONTROL + NULL MECHANICAL STATES
    # --------------------------------------------------------

    target = make_mechanical_state(
        "Target_native",
        target_coords,
        target_edges,
        cfg,
    )

    control = make_mechanical_state(
        "Control_native",
        control_coords,
        control_edges,
        cfg,
    )

    target_random = make_mechanical_state(
        "Target_MaslovSneppen_null",
        target_coords,
        target_random_edges,
        cfg,
    )

    # Eigenvector orthonormality assertions.
    for state in (
        target,
        control,
        target_random,
    ):

        n_modes = (
            state.eigenvectors.shape[1]
        )

        assert np.allclose(
            state.eigenvectors.T
            @ state.eigenvectors,
            np.eye(n_modes),
            atol=1e-8,
        )

    # --------------------------------------------------------
    # 5. CAUSAL ABLATION EXPERIMENT
    # --------------------------------------------------------

    (
        target_top,
        null_top,
        target_random_ablation,
        random_deltas,
        ablation_metadata,
    ) = build_comparative_states(
        target,
        target_random,
        cfg,
        rng,
    )

    (
        top_delta,
        top_lambda,
        null_top_delta,
        null_top_lambda,
    ) = ablation_metadata

    random_q025, random_q975 = (
        np.quantile(
            random_deltas,
            [0.025, 0.975],
        )
    )

    outside_95 = bool(
        top_delta < random_q025
        or top_delta > random_q975
    )

    empirical_p = (
        empirical_two_sided_p(
            top_delta,
            random_deltas,
        )
    )

    median_random_abs = float(
        np.median(
            np.abs(
                random_deltas
            )
        )
    )

    leverage_ablation_ratio = (
        abs(top_delta)
        / max(
            median_random_abs,
            cfg.density_floor,
        )
    )

    # --------------------------------------------------------
    # 6. LEVERAGE DISTRIBUTIONS
    # --------------------------------------------------------

    density_states = [
        target,
        control,
        target_random,
        target_top,
        target_random_ablation,
        null_top,
    ]

    bins, densities = (
        prepare_common_leverage_density(
            density_states,
            cfg,
        )
    )

    # Reference = average baseline density.
    # This is a statistical reference, not a fitted physical bath.
    baseline_density = np.mean(
        np.stack(
            [
                densities[target.name],
                densities[control.name],
                densities[target_random.name],
            ],
            axis=0,
        ),
        axis=0,
    )

    tv_by_state: Dict[str, float] = {}
    gamma_by_state: Dict[str, float] = {}

    for state in density_states:

        tv = total_variation_from_hist(
            densities[state.name],
            baseline_density,
            bins,
        )

        gamma = gamma_from_tv(
            tv,
            cfg,
        )

        tv_by_state[state.name] = tv
        gamma_by_state[state.name] = gamma

    # --------------------------------------------------------
    # 7. 4x4 LINDBLAD CLOSURE
    # --------------------------------------------------------

    (
        H_spin,
        P_S,
        jump_ops,
    ) = build_spin_hamiltonian(
        cfg
    )

    trajectory_names = [
        "Target_native",
        "Target_MaslovSneppen_null",
        "Target_top5pct_ablation",
        "Target_random5pct_ablation",
    ]

    trajectories = {}

    for state_name in trajectory_names:

        t, Y = integrate_lindblad(
            gamma_by_state[state_name],
            cfg,
            H_spin,
            P_S,
            jump_ops,
        )

        trajectories[state_name] = (
            t,
            Y,
        )

    # --------------------------------------------------------
    # 8. REPORT
    # --------------------------------------------------------

    print()
    print("=" * 78)
    print("TQS v8.0 | STANDALONE SYNTHETIC END-TO-END RUN")
    print("=" * 78)

    print(
        f"Cutoff = {cfg.cutoff_A:.2f} Å"
        f" | spring k = {cfg.spring_k:.2f}"
    )

    print(
        f"Target:  N={cfg.target_n}, "
        f"E={target_edges.shape[0]}, "
        f"degree=({target_degree.min()}, "
        f"{target_degree.max()})"
    )

    control_degree = degree_sequence(
        control_edges,
        cfg.control_n,
    )

    print(
        f"Control: N={cfg.control_n}, "
        f"E={control_edges.shape[0]}, "
        f"degree=({control_degree.min()}, "
        f"{control_degree.max()})"
    )

    print(
        f"Maslov-Sneppen accepted swaps = "
        f"{accepted_swaps:,}"
    )

    print(
        f"Maslov-Sneppen attempts = "
        f"{swap_attempts:,}"
    )

    print(
        f"Degree sequence invariant = "
        f"{np.array_equal(target_degree, target_random_degree)}"
    )

    print()
    print("---- LEVERAGE METRICS ----")

    for state in (
        target,
        control,
        target_random,
        target_top,
        target_random_ablation,
        null_top,
    ):
        print(
            format_metrics(state)
        )

    print()
    print("---- TARGETED ABLATION FALSIFICATION ----")

    print(
        "Top-5% Δlambda_min+ = "
        f"{top_delta:.8e}"
    )

    print(
        "Random-null 95% interval = "
        f"[{random_q025:.8e}, "
        f"{random_q975:.8e}]"
    )

    print(
        "Outside 95% null boundary = "
        f"{outside_95}"
    )

    print(
        "Empirical two-sided p = "
        f"{empirical_p:.4f}"
    )

    print(
        "Median |random Δlambda| = "
        f"{median_random_abs:.8e}"
    )

    print(
        "Top/random magnitude ratio = "
        f"{leverage_ablation_ratio:.3f}"
    )

    print()
    print("---- QUANTUM CLOSURE ----")

    for state_name in trajectory_names:

        endpoint = trajectories[
            state_name
        ][1][-1]

        print(
            f"{state_name:31s} "
            f"TV={tv_by_state[state_name]:.6f} "
            f"gamma_eff="
            f"{gamma_by_state[state_name]:.6f} μs^-1 "
            f"Y_S(5 μs)="
            f"{endpoint:.6f}"
        )

    print()
    print(
        "Note: gamma_eff is a phenomenological "
        "TV-based closure, not an experimentally "
        "calibrated radical-pair rate."
    )

    # --------------------------------------------------------
    # 9. DASHBOARD
    # --------------------------------------------------------

    fig, axes = plt.subplots(
        1,
        2,
        figsize=(15.5, 6.2),
        facecolor="#111111",
    )

    for ax in axes:

        ax.set_facecolor(
            "#111111"
        )

        ax.tick_params(
            colors="white"
        )

        for spine in ax.spines.values():
            spine.set_color(
                "white"
            )

        ax.xaxis.label.set_color(
            "white"
        )

        ax.yaxis.label.set_color(
            "white"
        )

        ax.title.set_color(
            "white"
        )

    # --------------------------------------------------------
    # PANEL 1
    # --------------------------------------------------------

    centers = 0.5 * (
        bins[:-1]
        + bins[1:]
    )

    panel1_states = [
        (
            target.name,
            "Target native",
        ),
        (
            control.name,
            "Control native",
        ),
        (
            target_random.name,
            "Target Maslov–Sneppen null",
        ),
    ]

    for state_name, label in panel1_states:

        axes[0].plot(
            centers,
            densities[state_name],
            linewidth=2.0,
            label=label,
        )

    axes[0].set_title(
        "P(Lₑ): edge spectral control landscape"
    )

    axes[0].set_xlabel(
        "Edge leverage Lₑ"
    )

    axes[0].set_ylabel(
        "Probability density"
    )

    axes[0].legend(
        frameon=False,
        labelcolor="white",
    )

    axes[0].grid(
        alpha=0.15
    )

    # --------------------------------------------------------
    # PANEL 2
    # --------------------------------------------------------

    panel2_states = [
        (
            "Target_native",
            "Target native",
        ),
        (
            "Target_MaslovSneppen_null",
            "Target null",
        ),
        (
            "Target_top5pct_ablation",
            "Top-leverage ablation",
        ),
        (
            "Target_random5pct_ablation",
            "Random 5% ablation",
        ),
    ]

    for state_name, label in panel2_states:

        t, Y = trajectories[
            state_name
        ]

        axes[1].plot(
            t,
            Y,
            linewidth=2.0,
            label=label,
        )

    axes[1].set_title(
        "Y_S(t): Lindblad singlet-fraction trajectories"
    )

    axes[1].set_xlabel(
        "Time (μs)"
    )

    axes[1].set_ylabel(
        "Singlet fraction Y_S(t)"
    )

    axes[1].set_ylim(
        -0.02,
        1.02,
    )

    axes[1].legend(
        frameon=False,
        labelcolor="white",
    )

    axes[1].grid(
        alpha=0.15
    )

    fig.suptitle(
        "Topological Spectral Susceptibility Model v8.0",
        color="white",
        fontsize=15,
        y=1.02,
    )

    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    main()