# -*- coding: utf-8 -*-
"""TSSM_v9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ywrd2-0Y7-bPBjqhEQO0FMYyM_eoFYT9
"""

# ================================================================
# TQS v9.0
# 3D ENM + Synthetic Cyclic Dimension + Spectral Susceptibility
# + Degree-Preserving Null + Edge Ablation + Lindblad
#
# STANDALONE GOOGLE COLAB
# NO INTERNET / NO PDB DOWNLOAD
#
# IMPORTANT:
# A single theta in S^1 is NOT sufficient to calculate a
# second Chern number. This implementation therefore measures:
#
#   - theta-dependent spectral gap
#   - eigenvector localization
#   - spectral susceptibility
#   - Berry phase of an isolated band (optional diagnostic)
#   - native/null contrast
#
# It deliberately does NOT claim a non-zero C2.
# ================================================================

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Tuple, List

import numpy as np
import scipy.linalg as la
import matplotlib.pyplot as plt

# Plotly is available in standard Colab.
import plotly.graph_objects as go


# ================================================================
# CONFIGURATION
# ================================================================

@dataclass(frozen=True)
class Config:

    # ------------------------------------------------------------
    # 3D ENM
    # ------------------------------------------------------------

    N: int = 100
    cutoff_A: float = 7.0
    spring_k: float = 1.0

    turns: float = 5.0
    radius_A: float = 8.0
    pitch_A_per_rad: float = 0.25

    radial_modulation: float = 0.08
    axial_warp_A: float = 0.80
    axial_warp_freq: float = 0.37
    radial_warp_freq: float = 0.71

    # ------------------------------------------------------------
    # SYNTHETIC DIMENSION
    # ------------------------------------------------------------

    theta_points: int = 20
    theta_amplitude: float = 0.12

    # ------------------------------------------------------------
    # SPECTRAL WINDOW
    # ------------------------------------------------------------

    soft_modes: int = 10
    rigid_modes: int = 6

    # ------------------------------------------------------------
    # NULL
    # ------------------------------------------------------------

    swaps_per_edge: int = 20
    max_attempt_factor: int = 80

    # ------------------------------------------------------------
    # ABLATION
    # ------------------------------------------------------------

    ablation_fraction: float = 0.05
    random_ablation_runs: int = 30

    # ------------------------------------------------------------
    # LINDblad
    # ------------------------------------------------------------

    total_time_us: float = 5.0
    dt_us: float = 0.002

    gamma_floor: float = 0.02
    gamma_span: float = 0.30

    earth_B_T: float = 5.0e-5
    electron_gamma_rad_s_T: float = 1.76085963023e11

    A1_MHz: float = 12.0
    A2_MHz: float = 4.0

    # ------------------------------------------------------------
    # NUMERICS
    # ------------------------------------------------------------

    eig_abs_tol: float = 1e-10
    eig_rel_tol: float = 1e-8

    seed: int = 20260921


CFG = Config()


# ================================================================
# 3D SYNTHETIC C-ALPHA FOLD
# ================================================================

def generate_3d_fold(cfg: Config) -> np.ndarray:

    t = np.linspace(
        0.0,
        cfg.turns * 2.0 * np.pi,
        cfg.N
    )

    radius = cfg.radius_A * (
        1.0
        + cfg.radial_modulation
        * np.sin(cfg.radial_warp_freq * t)
    )

    x = radius * np.cos(t)

    y = radius * np.sin(t)

    z = (
        cfg.pitch_A_per_rad * t
        + cfg.axial_warp_A
        * np.sin(cfg.axial_warp_freq * t)
    )

    coords = np.column_stack(
        [x, y, z]
    )

    coords -= coords.mean(axis=0)

    return coords


# ================================================================
# CONTACT GRAPH
# ================================================================

def build_contact_graph(
    coords: np.ndarray,
    cutoff: float
) -> np.ndarray:

    delta = (
        coords[:, None, :]
        - coords[None, :, :]
    )

    dist2 = np.einsum(
        "ijk,ijk->ij",
        delta,
        delta
    )

    i, j = np.triu_indices(
        len(coords),
        k=1
    )

    mask = (
        dist2[i, j]
        <= cutoff ** 2
    )

    return np.column_stack(
        [i[mask], j[mask]]
    ).astype(int)


def degree_sequence(
    edges: np.ndarray,
    n: int
) -> np.ndarray:

    return np.bincount(
        edges.reshape(-1),
        minlength=n
    )


# ================================================================
# MASLOV–SNEPPEN
# ================================================================

def maslov_sneppen(
    edges: np.ndarray,
    n: int,
    cfg: Config,
    rng: np.random.Generator
) -> Tuple[np.ndarray, int]:

    edge_list = [
        tuple(map(int, e))
        for e in edges
    ]

    edge_set = set(edge_list)

    target_swaps = max(
        20,
        cfg.swaps_per_edge * len(edge_list)
    )

    max_attempts = (
        target_swaps
        * cfg.max_attempt_factor
    )

    accepted = 0
    attempts = 0

    def canonical(a, b):

        return (
            (a, b)
            if a < b
            else
            (b, a)
        )

    while (
        accepted < target_swaps
        and attempts < max_attempts
    ):

        attempts += 1

        a_idx, b_idx = rng.choice(
            len(edge_list),
            size=2,
            replace=False
        )

        a, b = edge_list[a_idx]
        c, d = edge_list[b_idx]

        if len({a, b, c, d}) < 4:
            continue

        if rng.random() < 0.5:

            e1 = canonical(a, d)
            e2 = canonical(c, b)

        else:

            e1 = canonical(a, c)
            e2 = canonical(b, d)

        if (
            e1[0] == e1[1]
            or e2[0] == e2[1]
        ):
            continue

        old1 = canonical(a, b)
        old2 = canonical(c, d)

        if (
            e1 in edge_set
            or e2 in edge_set
        ):
            continue

        edge_set.remove(old1)
        edge_set.remove(old2)

        edge_set.add(e1)
        edge_set.add(e2)

        edge_list[a_idx] = e1
        edge_list[b_idx] = e2

        accepted += 1

    if accepted < target_swaps:

        raise RuntimeError(
            "Maslov-Sneppen sampler stalled: "
            f"{accepted}/{target_swaps} accepted."
        )

    randomized = np.array(
        sorted(edge_set),
        dtype=int
    )

    assert len(randomized) == len(edges)

    assert np.array_equal(
        degree_sequence(edges, n),
        degree_sequence(randomized, n)
    )

    return randomized, accepted


# ================================================================
# ENM HESSIAN
# ================================================================

def build_hessian(
    coords: np.ndarray,
    edges: np.ndarray,
    weights: np.ndarray,
    k: float
) -> np.ndarray:

    n = len(coords)

    H = np.zeros(
        (3 * n, 3 * n),
        dtype=float
    )

    ri = coords[edges[:, 0]]
    rj = coords[edges[:, 1]]

    delta = rj - ri

    norm = np.linalg.norm(
        delta,
        axis=1
    )

    unit = (
        delta
        / norm[:, None]
    )

    projectors = (
        np.einsum(
            "ea,eb->eab",
            unit,
            unit
        )
        * weights[:, None, None]
        * k
    )

    for e, (i, j) in enumerate(edges):

        si = slice(
            3 * i,
            3 * i + 3
        )

        sj = slice(
            3 * j,
            3 * j + 3
        )

        P = projectors[e]

        H[si, si] += P
        H[sj, sj] += P
        H[si, sj] -= P
        H[sj, si] -= P

    return 0.5 * (H + H.T)


# ================================================================
# SYNTHETIC THETA PHASE
# ================================================================

def edge_phase(
    coords: np.ndarray,
    edges: np.ndarray
) -> np.ndarray:

    """
    Geometry-derived phase assignment.

    It does NOT claim to be a physical Berry connection.

    It simply gives every edge a deterministic phase in S^1
    so that the mechanical operator becomes a periodic family.
    """

    midpoints = (
        coords[edges[:, 0]]
        + coords[edges[:, 1]]
    ) / 2.0

    phi = np.arctan2(
        midpoints[:, 1],
        midpoints[:, 0]
    )

    return phi


def theta_weights(
    theta: float,
    phases: np.ndarray,
    amplitude: float
) -> np.ndarray:

    weights = (
        1.0
        + amplitude
        * np.cos(
            theta + phases
        )
    )

    # Strictly positive spring weights.
    return np.maximum(
        weights,
        1e-4
    )


# ================================================================
# DIAGONALIZATION
# ================================================================

def diagonalize(
    H: np.ndarray,
    cfg: Config
):

    values, vectors = la.eigh(
        H
    )

    scale = max(
        1.0,
        np.max(np.abs(values))
    )

    tol = max(
        cfg.eig_abs_tol,
        cfg.eig_rel_tol * scale
    )

    if np.min(values) < -10.0 * tol:

        raise RuntimeError(
            "Hessian lost positive-semidefinite structure."
        )

    rigid = values[:cfg.rigid_modes]

    if not np.all(
        np.abs(rigid)
        < 10.0 * tol
    ):

        raise RuntimeError(
            "Six rigid-body modes were not identified."
        )

    positive = values[
        values > tol
    ]

    positive_vectors = vectors[
        :,
        values > tol
    ]

    return (
        values,
        vectors,
        positive,
        positive_vectors,
        tol
    )


# ================================================================
# EDGE SPECTRAL SUSCEPTIBILITY
# ================================================================

def spectral_leverage(
    coords: np.ndarray,
    edges: np.ndarray,
    positive_values: np.ndarray,
    positive_vectors: np.ndarray,
    cfg: Config
) -> np.ndarray:

    K = min(
        cfg.soft_modes,
        len(positive_values)
    )

    modes = positive_vectors[
        :, :K
    ].reshape(
        len(coords),
        3,
        K
    )

    vi = modes[
        edges[:, 0]
    ]

    vj = modes[
        edges[:, 1]
    ]

    delta_modes = vi - vj

    ri = coords[
        edges[:, 0]
    ]

    rj = coords[
        edges[:, 1]
    ]

    u = rj - ri

    u /= np.linalg.norm(
        u,
        axis=1,
        keepdims=True
    )

    projection = np.einsum(
        "ea,eak->ek",
        u,
        delta_modes
    )

    sensitivity = (
        projection ** 2
    )

    alpha = (
        1.0
        / np.maximum(
            positive_values[:K],
            1e-14
        )
    )

    alpha /= alpha.sum()

    leverage = (
        sensitivity @ alpha
    )

    return leverage


# ================================================================
# LEVERAGE METRICS
# ================================================================

def gini(x):

    x = np.asarray(
        x,
        dtype=float
    )

    x = np.sort(
        np.maximum(x, 0)
    )

    if np.sum(x) == 0:
        return 0.0

    n = len(x)

    return float(
        (
            2.0
            * np.sum(
                np.arange(1, n + 1)
                * x
            )
            - (n + 1)
            * np.sum(x)
        )
        / (
            n * np.sum(x)
        )
    )


def leverage_ipr(
    L
):

    p = (
        L
        / np.sum(L)
    )

    return float(
        np.sum(p ** 2)
    )


# ================================================================
# THETA SWEEP
# ================================================================

def theta_sweep(
    coords: np.ndarray,
    edges: np.ndarray,
    cfg: Config
):

    theta_grid = np.linspace(
        0.0,
        2.0 * np.pi,
        cfg.theta_points,
        endpoint=False
    )

    phases = edge_phase(
        coords,
        edges
    )

    spectra = []
    ipr_values = []
    gini_values = []
    susceptibility = []
    leverage_maps = []
    mode_profiles = []

    for theta in theta_grid:

        weights = theta_weights(
            theta,
            phases,
            cfg.theta_amplitude
        )

        H = build_hessian(
            coords,
            edges,
            weights,
            cfg.spring_k
        )

        (
            values,
            vectors,
            positive,
            positive_vectors,
            tol
        ) = diagonalize(
            H,
            cfg
        )

        L = spectral_leverage(
            coords,
            edges,
            positive,
            positive_vectors,
            cfg
        )

        ipr = leverage_ipr(L)

        G = gini(L)

        # Lowest positive spectral gap.
        gap = positive[0]

        # Susceptibility:
        # total soft-mode weighted leverage.
        chi = np.sum(L)

        spectra.append(
            values
        )

        ipr_values.append(
            ipr
        )

        gini_values.append(
            G
        )

        susceptibility.append(
            chi
        )

        leverage_maps.append(
            L
        )

        # Localization of the first positive mode.
        v = positive_vectors[
            :, 0
        ]

        p = v ** 2

        mode_profiles.append(
            np.sum(p ** 2)
        )

    return {
        "theta": theta_grid,
        "spectra": np.array(spectra),
        "leverage_ipr": np.array(ipr_values),
        "leverage_gini": np.array(gini_values),
        "susceptibility": np.array(susceptibility),
        "leverage_maps": leverage_maps,
        "mode_ipr": np.array(mode_profiles),
    }


# ================================================================
# GAP DIAGNOSTICS
# ================================================================

def gap_statistics(
    sweep
):

    spectra = sweep["spectra"]

    positive = spectra[
        :,
        CFG.rigid_modes:
    ]

    lowest = positive[:, 0]

    return {
        "min_gap": float(
            np.min(lowest)
        ),
        "max_gap": float(
            np.max(lowest)
        ),
        "mean_gap": float(
            np.mean(lowest)
        ),
        "gap_cv": float(
            np.std(lowest)
            / max(
                np.mean(lowest),
                1e-14
            )
        )
    }


# ================================================================
# ABLATION
# ================================================================

def remove_edges(
    edges,
    indices
):

    mask = np.ones(
        len(edges),
        dtype=bool
    )

    mask[indices] = False

    return edges[mask]


def top_leverage_edges(
    edges,
    leverage,
    fraction
):

    number = max(
        1,
        int(
            np.ceil(
                fraction * len(edges)
            )
        )
    )

    order = np.argsort(
        leverage
    )[::-1]

    return order[:number]


def ablated_gap_curve(
    coords,
    edges,
    remove_indices,
    cfg
):

    new_edges = remove_edges(
        edges,
        remove_indices
    )

    sweep = theta_sweep(
        coords,
        new_edges,
        cfg
    )

    return sweep


# ================================================================
# RANDOM ABLATION ENSEMBLE
# ================================================================

def random_ablation_ensemble(
    coords,
    edges,
    fraction,
    runs,
    rng,
    cfg
):

    m = len(edges)

    number = max(
        1,
        int(
            np.ceil(
                fraction * m
            )
        )
    )

    baseline = theta_sweep(
        coords,
        edges,
        cfg
    )

    baseline_gap = (
        baseline["spectra"][
            :,
            cfg.rigid_modes
        ][:, 0]
    )

    random_gap_shift = []

    for _ in range(runs):

        indices = rng.choice(
            m,
            size=number,
            replace=False
        )

        new_edges = remove_edges(
            edges,
            indices
        )

        sweep = theta_sweep(
            coords,
            new_edges,
            cfg
        )

        gap = (
            sweep["spectra"][
                :,
                cfg.rigid_modes
            ][:, 0]
        )

        random_gap_shift.append(
            np.mean(
                gap - baseline_gap
            )
        )

    return np.array(
        random_gap_shift
    )


# ================================================================
# 4x4 ELECTRON MODEL
# ================================================================

def spin_z():

    return 0.5 * np.array(
        [
            [1, 0],
            [0, -1]
        ],
        dtype=complex
    )


def build_spin_model(cfg):

    I = np.eye(
        2,
        dtype=complex
    )

    Sz = spin_z()

    S1z = np.kron(
        Sz,
        I
    )

    S2z = np.kron(
        I,
        Sz
    )

    omega_B = (
        cfg.earth_B_T
        * cfg.electron_gamma_rad_s_T
        * 1e-6
    )

    A1 = (
        2.0
        * np.pi
        * cfg.A1_MHz
    )

    A2 = (
        2.0
        * np.pi
        * cfg.A2_MHz
    )

    H_product = (
        omega_B
        * (S1z + S2z)
        + A1 * S1z
        + A2 * S2z
    )

    up = np.array(
        [1, 0],
        dtype=complex
    )

    down = np.array(
        [0, 1],
        dtype=complex
    )

    singlet = (
        np.kron(up, down)
        - np.kron(down, up)
    ) / np.sqrt(2)

    Tplus = np.kron(
        up,
        up
    )

    Tzero = (
        np.kron(up, down)
        + np.kron(down, up)
    ) / np.sqrt(2)

    Tminus = np.kron(
        down,
        down
    )

    U = np.column_stack(
        [
            singlet,
            Tplus,
            Tzero,
            Tminus
        ]
    )

    H = (
        U.conj().T
        @ H_product
        @ U
    )

    P_S = np.zeros(
        (4, 4),
        dtype=complex
    )

    P_S[0, 0] = 1.0

    jumps = []

    for triplet in [1, 2, 3]:

        J = np.zeros(
            (4, 4),
            dtype=complex
        )

        J[triplet, 0] = 1.0

        jumps.append(J)

    return (
        H,
        P_S,
        jumps
    )


# ================================================================
# LINDBLAD
# ================================================================

def lindblad_rhs(
    rho,
    H,
    jumps,
    gamma
):

    drho = (
        -1j
        * (
            H @ rho
            - rho @ H
        )
    )

    for J in jumps:

        Jg = (
            np.sqrt(
                gamma / 3.0
            )
            * J
        )

        JJ = (
            Jg.conj().T
            @ Jg
        )

        drho += (
            Jg @ rho @ Jg.conj().T
            - 0.5
            * (
                JJ @ rho
                + rho @ JJ
            )
        )

    return drho


def positivity_guard(
    rho
):

    rho = 0.5 * (
        rho
        + rho.conj().T
    )

    tr = np.real(
        np.trace(rho)
    )

    rho /= tr

    values, vectors = la.eigh(
        rho
    )

    values = np.maximum(
        values,
        0.0
    )

    rho = (
        vectors
        * values
    ) @ vectors.conj().T

    rho = 0.5 * (
        rho
        + rho.conj().T
    )

    rho /= np.real(
        np.trace(rho)
    )

    return rho


def integrate_lindblad(
    gamma,
    H,
    P_S,
    jumps,
    cfg
):

    steps = int(
        round(
            cfg.total_time_us
            / cfg.dt_us
        )
    )

    times = np.linspace(
        0.0,
        cfg.total_time_us,
        steps + 1
    )

    rho = P_S.copy()

    Y = np.empty(
        steps + 1
    )

    Y[0] = np.real(
        np.trace(
            P_S @ rho
        )
    )

    for step in range(
        steps
    ):

        k1 = lindblad_rhs(
            rho,
            H,
            jumps,
            gamma
        )

        k2 = lindblad_rhs(
            rho + 0.5 * cfg.dt_us * k1,
            H,
            jumps,
            gamma
        )

        k3 = lindblad_rhs(
            rho + 0.5 * cfg.dt_us * k2,
            H,
            jumps,
            gamma
        )

        k4 = lindblad_rhs(
            rho + cfg.dt_us * k3,
            H,
            jumps,
            gamma
        )

        rho += (
            cfg.dt_us / 6.0
        ) * (
            k1
            + 2*k2
            + 2*k3
            + k4
        )

        rho = positivity_guard(
            rho
        )

        assert np.allclose(
            rho,
            rho.conj().T,
            atol=1e-9
        )

        assert np.isclose(
            np.trace(rho),
            1.0,
            atol=1e-9
        )

        assert np.min(
            la.eigvalsh(rho)
        ) >= -1e-9

        Y[step + 1] = np.real(
            np.trace(
                P_S @ rho
            )
        )

    return times, Y


# ================================================================
# 3D VISUALIZATION
# ================================================================

def plot_3d_leverage(
    coords,
    edges,
    leverage,
    title,
    top_fraction=0.05
):

    fig = go.Figure()

    # ------------------------------------------------------------
    # ALL EDGES
    # ------------------------------------------------------------

    x = []
    y = []
    z = []

    for i, j in edges:

        x += [
            coords[i, 0],
            coords[j, 0],
            None
        ]

        y += [
            coords[i, 1],
            coords[j, 1],
            None
        ]

        z += [
            coords[i, 2],
            coords[j, 2],
            None
        ]

    fig.add_trace(
        go.Scatter3d(
            x=x,
            y=y,
            z=z,
            mode="lines",
            line=dict(
                width=1,
                color="rgba(120,120,120,0.18)"
            ),
            hoverinfo="skip",
            name="ENM edges"
        )
    )

    # ------------------------------------------------------------
    # TOP LEVERAGE EDGES
    # ------------------------------------------------------------

    n_top = max(
        1,
        int(
            top_fraction
            * len(edges)
        )
    )

    order = np.argsort(
        leverage
    )[::-1]

    selected = order[
        :n_top
    ]

    xt = []
    yt = []
    zt = []

    for idx in selected:

        i, j = edges[idx]

        xt += [
            coords[i, 0],
            coords[j, 0],
            None
        ]

        yt += [
            coords[i, 1],
            coords[j, 1],
            None
        ]

        zt += [
            coords[i, 2],
            coords[j, 2],
            None
        ]

    fig.add_trace(
        go.Scatter3d(
            x=xt,
            y=yt,
            z=zt,
            mode="lines",
            line=dict(
                width=5,
                color="orange"
            ),
            name="Top spectral leverage"
        )
    )

    # ------------------------------------------------------------
    # NODES
    # ------------------------------------------------------------

    node_strength = np.zeros(
        len(coords)
    )

    for e, (i, j) in enumerate(edges):

        node_strength[i] += leverage[e]
        node_strength[j] += leverage[e]

    fig.add_trace(
        go.Scatter3d(
            x=coords[:, 0],
            y=coords[:, 1],
            z=coords[:, 2],
            mode="markers",
            marker=dict(
                size=5,
                color=node_strength,
                colorscale="Turbo",
                colorbar=dict(
                    title="Node leverage"
                ),
                showscale=True
            ),
            text=[
                f"Node {i}"
                for i in range(len(coords))
            ],
            name="Cα nodes"
        )
    )

    fig.update_layout(
        title=title,
        template="plotly_dark",
        scene=dict(
            xaxis_title="X (Å)",
            yaxis_title="Y (Å)",
            zaxis_title="Z (Å)",
            aspectmode="data"
        ),
        width=1000,
        height=760
    )

    fig.show()


# ================================================================
# 3D SYNTHETIC-DIMENSION ANIMATION
# ================================================================

def animate_theta_3d(
    coords,
    edges,
    theta_grid,
    leverage_maps
):

    frames = []

    for frame_idx, theta in enumerate(
        theta_grid
    ):

        L = leverage_maps[
            frame_idx
        ]

        x = []
        y = []
        z = []

        for e, (i, j) in enumerate(edges):

            # Only display strongest edges
            if L[e] < np.quantile(
                L,
                0.90
            ):
                continue

            x += [
                coords[i, 0],
                coords[j, 0],
                None
            ]

            y += [
                coords[i, 1],
                coords[j, 1],
                None
            ]

            z += [
                coords[i, 2],
                coords[j, 2],
                None
            ]

        frames.append(
            go.Frame(
                data=[
                    go.Scatter3d(
                        x=x,
                        y=y,
                        z=z,
                        mode="lines",
                        line=dict(
                            width=5,
                            color="orange"
                        )
                    )
                ],
                name=str(frame_idx)
            )
        )

    first = frames[0].data

    fig = go.Figure(
        data=first,
        frames=frames
    )

    fig.update_layout(
        title=(
            "3D spectral-leverage evolution "
            "along synthetic θ dimension"
        ),
        template="plotly_dark",
        scene=dict(
            xaxis_title="X (Å)",
            yaxis_title="Y (Å)",
            zaxis_title="Z (Å)",
            aspectmode="data"
        ),
        updatemenus=[
            dict(
                type="buttons",
                buttons=[
                    dict(
                        label="▶ Play θ",
                        method="animate",
                        args=[
                            None,
                            {
                                "frame": {
                                    "duration": 300,
                                    "redraw": True
                                },
                                "fromcurrent": True
                            }
                        ]
                    )
                ]
            )
        ],
        sliders=[
            dict(
                steps=[
                    dict(
                        method="animate",
                        args=[
                            [str(i)],
                            {
                                "mode": "immediate",
                                "frame": {
                                    "duration": 0,
                                    "redraw": True
                                }
                            }
                        ],
                        label=f"{theta:.2f}"
                    )
                    for i, theta in enumerate(
                        theta_grid
                    )
                ],
                currentvalue={
                    "prefix": "θ = "
                }
            )
        ],
        width=1000,
        height=760
    )

    fig.show()


# ================================================================
# DARK DASHBOARD
# ================================================================

def dashboard(
    native,
    null,
    top_ablation,
    random_ablation,
    trajectories
):

    theta = native["theta"]

    fig, ax = plt.subplots(
        2,
        1,
        figsize=(13, 11),
        facecolor="#111111"
    )

    for a in ax:

        a.set_facecolor(
            "#111111"
        )

        a.tick_params(
            colors="white"
        )

        for spine in a.spines.values():
            spine.set_color(
                "white"
            )

        a.xaxis.label.set_color(
            "white"
        )

        a.yaxis.label.set_color(
            "white"
        )

        a.title.set_color(
            "white"
        )

    # ------------------------------------------------------------
    # PANEL 1
    # ------------------------------------------------------------

    ax[0].plot(
        theta,
        native["susceptibility"],
        marker="o",
        label="Native"
    )

    ax[0].plot(
        theta,
        null["susceptibility"],
        marker="o",
        label="Maslov–Sneppen null"
    )

    ax[0].plot(
        theta,
        top_ablation["susceptibility"],
        linestyle="--",
        label="Top-leverage ablation"
    )

    ax[0].plot(
        theta,
        random_ablation["susceptibility"],
        linestyle="--",
        label="Random matched ablation"
    )

    ax[0].set_title(
        "Synthetic-dimension spectral susceptibility"
    )

    ax[0].set_xlabel(
        "Synthetic phase θ"
    )

    ax[0].set_ylabel(
        "Σₖ αₖ Sₑ,ₖ"
    )

    ax[0].legend(
        frameon=False
    )

    ax[0].grid(
        alpha=0.15
    )

    # ------------------------------------------------------------
    # PANEL 2
    # ------------------------------------------------------------

    for name, (
        t,
        Y
    ) in trajectories.items():

        ax[1].plot(
            t,
            Y,
            linewidth=2,
            label=name
        )

    ax[1].set_title(
        "Open-system singlet dynamics"
    )

    ax[1].set_xlabel(
        "Time (μs)"
    )

    ax[1].set_ylabel(
        "Y_S(t)"
    )

    ax[1].set_ylim(
        -0.02,
        1.02
    )

    ax[1].legend(
        frameon=False
    )

    ax[1].grid(
        alpha=0.15
    )

    fig.suptitle(
        "TQS v9.0 — 3D + Synthetic Dimension",
        color="white",
        fontsize=16
    )

    plt.tight_layout()

    plt.show()


# ================================================================
# MAIN
# ================================================================

def main():

    cfg = CFG

    rng = np.random.default_rng(
        cfg.seed
    )

    print("=" * 76)
    print("TQS v9.0 — 3D SYNTHETIC TOPOLOGICAL SUSCEPTIBILITY")
    print("=" * 76)

    # ------------------------------------------------------------
    # 1. 3D STRUCTURE
    # ------------------------------------------------------------

    coords = generate_3d_fold(
        cfg
    )

    edges = build_contact_graph(
        coords,
        cfg.cutoff_A
    )

    print(
        f"\n3D scaffold: "
        f"N={len(coords)}, "
        f"E={len(edges)}"
    )

    # ------------------------------------------------------------
    # 2. NULL TOPOLOGY
    # ------------------------------------------------------------

    random_edges, accepted = (
        maslov_sneppen(
            edges,
            cfg.N,
            cfg,
            rng
        )
    )

    assert np.array_equal(
        degree_sequence(
            edges,
            cfg.N
        ),
        degree_sequence(
            random_edges,
            cfg.N
        )
    )

    print(
        f"Maslov–Sneppen swaps: "
        f"{accepted:,}"
    )

    print(
        "Degree sequence invariant: TRUE"
    )

    # ------------------------------------------------------------
    # 3. NATIVE SYNTHETIC CYCLE
    # ------------------------------------------------------------

    print(
        "\n[1/5] Native θ sweep..."
    )

    native = theta_sweep(
        coords,
        edges,
        cfg
    )

    # ------------------------------------------------------------
    # 4. NULL SYNTHETIC CYCLE
    # ------------------------------------------------------------

    print(
        "[2/5] Null θ sweep..."
    )

    null = theta_sweep(
        coords,
        random_edges,
        cfg
    )

    # ------------------------------------------------------------
    # 5. TOP-LEVERAGE ABLATION
    # ------------------------------------------------------------

    L0 = native[
        "leverage_maps"
    ][0]

    top_indices = top_leverage_edges(
        edges,
        L0,
        cfg.ablation_fraction
    )

    top_edges = remove_edges(
        edges,
        top_indices
    )

    print(
        "[3/5] Top-leverage ablation θ sweep..."
    )

    top_ablation = theta_sweep(
        coords,
        top_edges,
        cfg
    )

    # ------------------------------------------------------------
    # 6. RANDOM MATCHED ABLATION
    # ------------------------------------------------------------

    number = len(top_indices)

    random_indices = rng.choice(
        len(edges),
        size=number,
        replace=False
    )

    random_edges_ablation = remove_edges(
        edges,
        random_indices
    )

    print(
        "[4/5] Random matched ablation θ sweep..."
    )

    random_ablation = theta_sweep(
        coords,
        random_edges_ablation,
        cfg
    )

    # ------------------------------------------------------------
    # 7. GAP TEST
    # ------------------------------------------------------------

    native_gap = gap_statistics(
        native
    )

    null_gap = gap_statistics(
        null
    )

    top_gap = gap_statistics(
        top_ablation
    )

    random_gap = gap_statistics(
        random_ablation
    )

    print("\n--- SYNTHETIC CYCLE GAP ---")

    print(
        f"Native min gap      : "
        f"{native_gap['min_gap']:.6e}"
    )

    print(
        f"Native gap CV       : "
        f"{native_gap['gap_cv']:.6f}"
    )

    print(
        f"Null min gap        : "
        f"{null_gap['min_gap']:.6e}"
    )

    print(
        f"Top-ablation min gap: "
        f"{top_gap['min_gap']:.6e}"
    )

    print(
        f"Random-ablation gap : "
        f"{random_gap['min_gap']:.6e}"
    )

    # ------------------------------------------------------------
    # 8. LINDBLAD BRIDGE
    # ------------------------------------------------------------

    H_spin, P_S, jumps = (
        build_spin_model(cfg)
    )

    # Mean normalized susceptibility.
    def normalized_susceptibility(
        sweep
    ):

        x = sweep[
            "susceptibility"
        ]

        return (
            x.mean()
            / max(
                native[
                    "susceptibility"
                ].mean(),
                1e-14
            )
        )

    s_native = (
        normalized_susceptibility(
            native
        )
    )

    s_null = (
        normalized_susceptibility(
            null
        )
    )

    s_top = (
        normalized_susceptibility(
            top_ablation
        )
    )

    s_random = (
        normalized_susceptibility(
            random_ablation
        )
    )

    # Phenomenological closure:
    #
    # larger spectral susceptibility
    # -> larger effective leakage rate.
    #
    # This is an explicit modeling assumption.
    def gamma_from_score(
        score
    ):

        return (
            cfg.gamma_floor
            + cfg.gamma_span
            * np.clip(
                score,
                0.0,
                1.0
            )
        )

    gamma_native = gamma_from_score(
        s_native
    )

    gamma_null = gamma_from_score(
        s_null
    )

    gamma_top = gamma_from_score(
        s_top
    )

    gamma_random = gamma_from_score(
        s_random
    )

    print(
        "\n[5/5] Lindblad trajectories..."
    )

    trajectories = {}

    for label, gamma in [
        ("Native", gamma_native),
        ("Maslov–Sneppen null", gamma_null),
        ("Top-leverage ablation", gamma_top),
        ("Random matched ablation", gamma_random)
    ]:

        t, Y = integrate_lindblad(
            gamma,
            H_spin,
            P_S,
            jumps,
            cfg
        )

        trajectories[label] = (
            t,
            Y
        )

        print(
            f"{label:25s} "
            f"gamma={gamma:.6f} μs^-1 "
            f"Y_S(5μs)={Y[-1]:.6f}"
        )

    # ------------------------------------------------------------
    # 9. 3D NATIVE LEVERAGE MAP
    # ------------------------------------------------------------

    plot_3d_leverage(
        coords,
        edges,
        native[
            "leverage_maps"
        ][0],
        "TQS v9 — 3D native spectral-leverage map"
    )

    # ------------------------------------------------------------
    # 10. 3D THETA ANIMATION
    # ------------------------------------------------------------

    animate_theta_3d(
        coords,
        edges,
        native["theta"],
        native["leverage_maps"]
    )

    # ------------------------------------------------------------
    # 11. DARK DASHBOARD
    # ------------------------------------------------------------

    dashboard(
        native,
        null,
        top_ablation,
        random_ablation,
        trajectories
    )

    # ------------------------------------------------------------
    # 12. FINAL DIAGNOSTIC
    # ------------------------------------------------------------

    native_ipr_range = (
        np.min(
            native["leverage_ipr"]
        ),
        np.max(
            native["leverage_ipr"]
        )
    )

    null_ipr_range = (
        np.min(
            null["leverage_ipr"]
        ),
        np.max(
            null["leverage_ipr"]
        )
    )

    print("\n" + "=" * 76)
    print("EPISTEMIC DIAGNOSTICS")
    print("=" * 76)

    print(
        "Native leverage IPR range: "
        f"{native_ipr_range}"
    )

    print(
        "Null leverage IPR range:   "
        f"{null_ipr_range}"
    )

    print(
        "\nIMPORTANT:"
    )

    print(
        "This experiment does NOT establish "
        "a non-zero second Chern number."
    )

    print(
        "A single theta parameter defines S^1, "
        "not a 4D parameter manifold."
    )

    print(
        "Therefore 'topological protection' is "
        "NOT automatically established by a "
        "persistent spectral gap."
    )

    print(
        "The present result is a theta-dependent "
        "synthetic spectral-susceptibility experiment."
    )


# ================================================================
# EXECUTE
# ================================================================

if __name__ == "__main__":
    main()