# -*- coding: utf-8 -*-
"""TMMS_v9.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wsuSrkbOAXaxf5e61FXN4HOTSQhcpsAx
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Tuple, List

import numpy as np
from scipy import linalg as la
import matplotlib.pyplot as plt
import plotly.graph_objects as go


@dataclass(frozen=True)
class Config:
    N: int = 100
    cutoff_A: float = 7.0
    spring_k: float = 1.0

    turns: float = 5.0
    radius_A: float = 8.0
    pitch_A_per_rad: float = 0.25
    radial_modulation: float = 0.08
    axial_warp_A: float = 0.80
    axial_warp_freq: float = 0.37
    radial_warp_freq: float = 0.71

    theta_points: int = 20
    theta_amplitude: float = 0.30

    rigid_modes: int = 6
    soft_modes: int = 10
    ablation_fraction: float = 0.05
    random_ablation_runs: int = 30

    swaps_per_edge: int = 20
    max_attempt_factor: int = 80

    total_time_us: float = 5.0
    dt_us: float = 0.002
    gamma_floor: float = 0.02
    gamma_span: float = 0.30

    earth_B_T: float = 5.0e-5
    electron_gamma_rad_s_T: float = 1.76085963023e11
    A1_MHz: float = 12.0
    A2_MHz: float = 4.0

    eig_abs_tol: float = 1e-10
    eig_rel_tol: float = 1e-8
    seed: int = 20260921
    render_3d: bool = True


CFG = Config()


def generate_3d_fold(cfg: Config) -> np.ndarray:
    t = np.linspace(0.0, cfg.turns * 2.0 * np.pi, cfg.N)
    radius = cfg.radius_A * (1.0 + cfg.radial_modulation * np.sin(cfg.radial_warp_freq * t))
    x = radius * np.cos(t)
    y = radius * np.sin(t)
    z = cfg.pitch_A_per_rad * t + cfg.axial_warp_A * np.sin(cfg.axial_warp_freq * t)
    coords = np.column_stack((x, y, z))
    coords -= coords.mean(axis=0, keepdims=True)
    return coords


def build_contact_graph(coords: np.ndarray, cutoff: float) -> np.ndarray:
    delta = coords[:, None, :] - coords[None, :, :]
    dist2 = np.einsum("ijk,ijk->ij", delta, delta)
    i, j = np.triu_indices(len(coords), k=1)
    mask = dist2[i, j] <= cutoff * cutoff
    return np.column_stack((i[mask], j[mask])).astype(int)


def degree_sequence(edges: np.ndarray, n: int) -> np.ndarray:
    return np.bincount(edges.reshape(-1), minlength=n)


def maslov_sneppen(edges: np.ndarray, n: int, cfg: Config, rng: np.random.Generator) -> np.ndarray:
    edge_list = [tuple(map(int, e)) for e in edges]
    edge_set = set(edge_list)
    target_swaps = max(20, cfg.swaps_per_edge * len(edge_list))
    max_attempts = target_swaps * cfg.max_attempt_factor

    def canon(a: int, b: int) -> Tuple[int, int]:
        return (a, b) if a < b else (b, a)

    accepted = 0
    attempts = 0
    while accepted < target_swaps and attempts < max_attempts:
        attempts += 1
        i1, i2 = rng.choice(len(edge_list), size=2, replace=False)
        a, b = edge_list[i1]
        c, d = edge_list[i2]
        if len({a, b, c, d}) < 4:
            continue
        if rng.random() < 0.5:
            e1, e2 = canon(a, d), canon(c, b)
        else:
            e1, e2 = canon(a, c), canon(b, d)
        if e1[0] == e1[1] or e2[0] == e2[1]:
            continue
        old1, old2 = canon(a, b), canon(c, d)
        if e1 in edge_set or e2 in edge_set:
            continue
        edge_set.remove(old1)
        edge_set.remove(old2)
        edge_set.add(e1)
        edge_set.add(e2)
        edge_list[i1], edge_list[i2] = e1, e2
        accepted += 1

    if accepted < target_swaps:
        raise RuntimeError(f"Maslov-Sneppen stalled: {accepted}/{target_swaps} accepted.")

    randomized = np.array(sorted(edge_set), dtype=int)
    assert randomized.shape == edges.shape
    assert np.array_equal(degree_sequence(edges, n), degree_sequence(randomized, n))
    return randomized


def build_hessian(coords: np.ndarray, edges: np.ndarray, weights: np.ndarray, k: float) -> np.ndarray:
    n = len(coords)
    H = np.zeros((3 * n, 3 * n), dtype=float)

    ri = coords[edges[:, 0]]
    rj = coords[edges[:, 1]]
    delta = rj - ri
    norm = np.linalg.norm(delta, axis=1)
    if np.any(norm <= 0.0):
        raise ValueError("Zero-length edge encountered.")
    unit = delta / norm[:, None]
    projectors = np.einsum("ea,eb->eab", unit, unit) * weights[:, None, None] * k

    # Vectorized scatter-add over 3x3 edge blocks.
    axes = np.arange(3)[None, :]
    rows_i = 3 * edges[:, 0, None] + axes
    rows_j = 3 * edges[:, 1, None] + axes

    ii_r = np.broadcast_to(rows_i[:, :, None], projectors.shape)
    ii_c = np.broadcast_to(rows_i[:, None, :], projectors.shape)
    jj_r = np.broadcast_to(rows_j[:, :, None], projectors.shape)
    jj_c = np.broadcast_to(rows_j[:, None, :], projectors.shape)

    np.add.at(H, (ii_r.ravel(), ii_c.ravel()), projectors.ravel())
    np.add.at(H, (jj_r.ravel(), jj_c.ravel()), projectors.ravel())
    np.add.at(H, (ii_r.ravel(), jj_c.ravel()), -projectors.ravel())
    np.add.at(H, (jj_r.ravel(), ii_c.ravel()), -projectors.ravel())

    return 0.5 * (H + H.T)


def edge_phase(coords: np.ndarray, edges: np.ndarray) -> np.ndarray:
    midpoint = 0.5 * (coords[edges[:, 0]] + coords[edges[:, 1]])
    return np.arctan2(midpoint[:, 1], midpoint[:, 0])


def theta_weights(theta: float, phases: np.ndarray, amplitude: float) -> np.ndarray:
    return np.maximum(1.0 + amplitude * np.cos(theta + phases), 1e-4)


def diagonalize(H: np.ndarray, cfg: Config):
    values, vectors = la.eigh(H)
    scale = max(1.0, float(np.max(np.abs(values))))
    tol = max(cfg.eig_abs_tol, cfg.eig_rel_tol * scale)
    if np.min(values) < -10.0 * tol:
        raise RuntimeError(f"Hessian not PSD within tolerance: min={np.min(values):.3e}")
    if not np.all(np.abs(values[:cfg.rigid_modes]) < 10.0 * tol):
        raise RuntimeError("Six rigid-body modes were not identified within tolerance.")
    positive_mask = values > tol
    positive = values[positive_mask]
    positive_vectors = vectors[:, positive_mask]
    if len(positive) < cfg.soft_modes:
        raise RuntimeError("Insufficient positive modes.")
    return values, vectors, positive, positive_vectors, tol


def spectral_leverage(coords: np.ndarray, edges: np.ndarray, positive_values: np.ndarray, positive_vectors: np.ndarray, cfg: Config) -> np.ndarray:
    K = min(cfg.soft_modes, len(positive_values))
    modes = positive_vectors[:, :K].reshape(len(coords), 3, K)
    dv = modes[edges[:, 0]] - modes[edges[:, 1]]
    u = coords[edges[:, 1]] - coords[edges[:, 0]]
    u /= np.linalg.norm(u, axis=1, keepdims=True)
    projected = np.einsum("ea,eak->ek", u, dv)
    sensitivity = projected * projected
    alpha = 1.0 / np.maximum(positive_values[:K], 1e-14)
    alpha /= alpha.sum()
    return sensitivity @ alpha


def gini(x: np.ndarray) -> float:
    x = np.sort(np.maximum(np.asarray(x, dtype=float), 0.0))
    total = np.sum(x)
    if total <= 0.0:
        return 0.0
    n = len(x)
    return float((2.0 * np.sum(np.arange(1, n + 1) * x) - (n + 1) * total) / (n * total))


def leverage_ipr(L: np.ndarray) -> float:
    p = L / np.sum(L)
    return float(np.sum(p * p))


def leverage_node_strength(coords: np.ndarray, edges: np.ndarray, L: np.ndarray) -> np.ndarray:
    node_L = np.zeros(len(coords), dtype=float)
    np.add.at(node_L, edges[:, 0], L)
    np.add.at(node_L, edges[:, 1], L)
    return node_L


def subspace_projector(vectors: np.ndarray, K: int) -> np.ndarray:
    U = vectors[:, :K]
    return U @ U.T


def subspace_distance(P: np.ndarray, Q: np.ndarray) -> float:
    return float(la.norm(P - Q, ord="fro"))


def theta_sweep(coords: np.ndarray, edges: np.ndarray, cfg: Config) -> Dict[str, np.ndarray]:
    theta = np.linspace(0.0, 2.0 * np.pi, cfg.theta_points, endpoint=False)
    phases = edge_phase(coords, edges)

    spectra = []
    full_vectors = []
    positive_values = []
    leverage_maps = []
    gini_values = []
    ipr_values = []
    mode_ipr_values = []
    gaps = []
    susceptibility = []

    K = cfg.soft_modes

    for th in theta:
        w = theta_weights(th, phases, cfg.theta_amplitude)
        H = build_hessian(coords, edges, w, cfg.spring_k)
        values, vectors, positive, positive_vectors, _ = diagonalize(H, cfg)
        L = spectral_leverage(coords, edges, positive, positive_vectors, cfg)
        v = positive_vectors[:, 0]
        mode_p = v * v

        spectra.append(values)
        full_vectors.append(vectors)
        positive_values.append(positive[:K])
        leverage_maps.append(L)
        gini_values.append(gini(L))
        ipr_values.append(leverage_ipr(L))
        mode_ipr_values.append(float(np.sum(mode_p * mode_p)))
        gaps.append(float(positive[0]))
        susceptibility.append(float(np.sum(L)))

    leverage_matrix = np.asarray(leverage_maps)
    subspace_P = np.asarray([subspace_projector(V, K) for V in full_vectors])

    # Cyclic finite difference: spectral-control flux J_e(theta) = dL_e/dtheta.
    dtheta = 2.0 * np.pi / cfg.theta_points
    flux = (np.roll(leverage_matrix, -1, axis=0) - np.roll(leverage_matrix, 1, axis=0)) / (2.0 * dtheta)

    # Persistent top-5% membership through the synthetic cycle.
    threshold = np.quantile(leverage_matrix, 0.95, axis=1)
    top_mask = leverage_matrix >= threshold[:, None]
    persistence = np.mean(top_mask, axis=0)

    # Rank trajectory and its variability.
    ranks = np.empty_like(leverage_matrix, dtype=float)
    for t in range(len(theta)):
        order = np.argsort(np.argsort(-leverage_matrix[t]))
        ranks[t] = order + 1.0
    rank_volatility = np.std(ranks, axis=0)

    # Consecutive soft-subspace transport.
    subspace_transport = np.array([
        subspace_distance(subspace_P[t], subspace_P[(t + 1) % len(theta)])
        for t in range(len(theta))
    ])

    return {
        "theta": theta,
        "spectra": np.asarray(spectra),
        "vectors": np.asarray(full_vectors),
        "positive_values": np.asarray(positive_values),
        "leverage_maps": leverage_matrix,
        "leverage_gini": np.asarray(gini_values),
        "leverage_ipr": np.asarray(ipr_values),
        "mode_ipr": np.asarray(mode_ipr_values),
        "gap": np.asarray(gaps),
        "susceptibility": np.asarray(susceptibility),
        "subspace_projectors": subspace_P,
        "subspace_transport": subspace_transport,
        "spectral_flux": flux,
        "leverage_persistence": persistence,
        "rank_volatility": rank_volatility,
    }


def remove_edges(edges: np.ndarray, indices: np.ndarray) -> np.ndarray:
    mask = np.ones(len(edges), dtype=bool)
    mask[np.asarray(indices, dtype=int)] = False
    out = edges[mask]
    if len(out) == 0:
        raise RuntimeError("Ablation removed all edges.")
    return out


def select_persistent_edges(leverage_matrix: np.ndarray, fraction: float) -> np.ndarray:
    m = leverage_matrix.shape[1]
    n = max(1, int(np.ceil(fraction * m)))
    score = leverage_matrix.mean(axis=0)
    order = np.argsort(score)[::-1]
    return order[:n]


def lowest_positive_gap_only(
    coords: np.ndarray,
    edges: np.ndarray,
    cfg: Config,
) -> np.ndarray:
    theta = np.linspace(0.0, 2.0 * np.pi, cfg.theta_points, endpoint=False)
    phases = edge_phase(coords, edges)
    gaps = np.empty(cfg.theta_points, dtype=float)
    for t, th in enumerate(theta):
        w = theta_weights(th, phases, cfg.theta_amplitude)
        H = build_hessian(coords, edges, w, cfg.spring_k)
        # Only one eigenvalue is needed here: much cheaper than full diagonalization.
        vals = la.eigvalsh(H, subset_by_index=[cfg.rigid_modes, cfg.rigid_modes])
        gaps[t] = float(vals[0])
    return gaps


def random_ablation_theta_ensemble(
    coords: np.ndarray,
    edges: np.ndarray,
    fraction: float,
    runs: int,
    rng: np.random.Generator,
    cfg: Config,
) -> np.ndarray:
    n_remove = max(1, int(np.ceil(fraction * len(edges))))
    baseline_gap = lowest_positive_gap_only(coords, edges, cfg)
    outputs = np.empty(runs, dtype=float)
    for r in range(runs):
        idx = rng.choice(len(edges), size=n_remove, replace=False)
        e2 = remove_edges(edges, idx)
        gap = lowest_positive_gap_only(coords, e2, cfg)
        outputs[r] = float(np.mean(gap - baseline_gap))
    return outputs


def spin_z() -> np.ndarray:
    return 0.5 * np.array([[1, 0], [0, -1]], dtype=complex)


def build_spin_model(cfg: Config):
    I = np.eye(2, dtype=complex)
    Sz = spin_z()
    S1z = np.kron(Sz, I)
    S2z = np.kron(I, Sz)

    omega_B = cfg.earth_B_T * cfg.electron_gamma_rad_s_T * 1e-6
    A1 = 2.0 * np.pi * cfg.A1_MHz
    A2 = 2.0 * np.pi * cfg.A2_MHz
    H_product = omega_B * (S1z + S2z) + A1 * S1z + A2 * S2z

    up = np.array([1, 0], dtype=complex)
    down = np.array([0, 1], dtype=complex)
    singlet = (np.kron(up, down) - np.kron(down, up)) / np.sqrt(2.0)
    Tplus = np.kron(up, up)
    Tzero = (np.kron(up, down) + np.kron(down, up)) / np.sqrt(2.0)
    Tminus = np.kron(down, down)
    U = np.column_stack([singlet, Tplus, Tzero, Tminus])
    H = U.conj().T @ H_product @ U

    P_S = np.zeros((4, 4), dtype=complex)
    P_S[0, 0] = 1.0

    jumps = []
    for triplet in [1, 2, 3]:
        J = np.zeros((4, 4), dtype=complex)
        J[triplet, 0] = 1.0
        jumps.append(J)
    return H, P_S, jumps


def lindblad_rhs(rho, H, jumps, gamma):
    drho = -1j * (H @ rho - rho @ H)
    for J in jumps:
        Jg = np.sqrt(gamma / 3.0) * J
        JJ = Jg.conj().T @ Jg
        drho += Jg @ rho @ Jg.conj().T - 0.5 * (JJ @ rho + rho @ JJ)
    return drho


def positivity_guard(rho: np.ndarray) -> np.ndarray:
    rho = 0.5 * (rho + rho.conj().T)
    tr = float(np.real(np.trace(rho)))
    if tr <= 0.0:
        raise FloatingPointError("Density-matrix trace became non-positive.")
    rho /= tr
    vals, vecs = la.eigh(rho)
    vals = np.maximum(vals, 0.0)
    rho = (vecs * vals) @ vecs.conj().T
    rho = 0.5 * (rho + rho.conj().T)
    rho /= float(np.real(np.trace(rho)))
    return rho


def integrate_lindblad(gamma: float, H: np.ndarray, P_S: np.ndarray, jumps: List[np.ndarray], cfg: Config):
    steps = int(round(cfg.total_time_us / cfg.dt_us))
    times = np.linspace(0.0, cfg.total_time_us, steps + 1)
    rho = P_S.copy()
    Y = np.empty(steps + 1, dtype=float)
    Y[0] = float(np.real(np.trace(P_S @ rho)))

    for step in range(steps):
        dt = cfg.dt_us
        k1 = lindblad_rhs(rho, H, jumps, gamma)
        k2 = lindblad_rhs(rho + 0.5 * dt * k1, H, jumps, gamma)
        k3 = lindblad_rhs(rho + 0.5 * dt * k2, H, jumps, gamma)
        k4 = lindblad_rhs(rho + dt * k3, H, jumps, gamma)
        rho = rho + (dt / 6.0) * (k1 + 2.0 * k2 + 2.0 * k3 + k4)
        rho = positivity_guard(rho)

        assert np.allclose(rho, rho.conj().T, atol=1e-9)
        assert np.isclose(np.trace(rho), 1.0, atol=1e-9)
        assert np.min(la.eigvalsh(rho)) >= -1e-9
        Y[step + 1] = float(np.real(np.trace(P_S @ rho)))

    return times, Y


def score_to_gamma(score: float, cfg: Config) -> float:
    # Monotone but non-saturating phenomenological closure.
    # This is a modeling bridge, not a microscopic rate derivation.
    score = max(float(score), 0.0)
    compressed = score / (1.0 + score)
    return float(cfg.gamma_floor + cfg.gamma_span * compressed)


def normalized_cycle_score(sweep: Dict[str, np.ndarray], reference: Dict[str, np.ndarray]) -> float:
    return float(np.mean(sweep["susceptibility"]) / max(np.mean(reference["susceptibility"]), 1e-14))


def make_3d_leverage_plot(coords, edges, leverage, title):
    fig = go.Figure()
    x, y, z = [], [], []
    for i, j in edges:
        x += [coords[i, 0], coords[j, 0], None]
        y += [coords[i, 1], coords[j, 1], None]
        z += [coords[i, 2], coords[j, 2], None]
    fig.add_trace(go.Scatter3d(x=x, y=y, z=z, mode="lines", line=dict(width=1, color="rgba(140,140,140,0.22)"), hoverinfo="skip", name="ENM edges"))

    top = np.argsort(leverage)[::-1][:max(1, int(np.ceil(0.05 * len(edges))))]
    xt, yt, zt = [], [], []
    for e in top:
        i, j = edges[e]
        xt += [coords[i, 0], coords[j, 0], None]
        yt += [coords[i, 1], coords[j, 1], None]
        zt += [coords[i, 2], coords[j, 2], None]
    fig.add_trace(go.Scatter3d(x=xt, y=yt, z=zt, mode="lines", line=dict(width=5, color="orange"), name="Top 5% leverage"))

    node_strength = leverage_node_strength(coords, edges, leverage)
    fig.add_trace(go.Scatter3d(
        x=coords[:, 0], y=coords[:, 1], z=coords[:, 2], mode="markers",
        marker=dict(size=5, color=node_strength, colorscale="Turbo", colorbar=dict(title="Node leverage")),
        text=[f"Cα node {i}" for i in range(len(coords))], name="Cα nodes"
    ))
    fig.update_layout(
        title=title, template="plotly_dark", width=1000, height=760,
        scene=dict(xaxis_title="X (Å)", yaxis_title="Y (Å)", zaxis_title="Z (Å)", aspectmode="data")
    )
    fig.show()


def make_theta_animation(coords, edges, theta, leverage_matrix):
    frames = []
    for t, th in enumerate(theta):
        L = leverage_matrix[t]
        cut = np.quantile(L, 0.90)
        x, y, z = [], [], []
        for e, (i, j) in enumerate(edges):
            if L[e] < cut:
                continue
            x += [coords[i, 0], coords[j, 0], None]
            y += [coords[i, 1], coords[j, 1], None]
            z += [coords[i, 2], coords[j, 2], None]
        frames.append(go.Frame(data=[go.Scatter3d(x=x, y=y, z=z, mode="lines", line=dict(width=5, color="orange"))], name=str(t)))

    fig = go.Figure(data=frames[0].data, frames=frames)
    fig.update_layout(
        title="3D spectral-control flow across synthetic θ",
        template="plotly_dark", width=1000, height=760,
        scene=dict(xaxis_title="X (Å)", yaxis_title="Y (Å)", zaxis_title="Z (Å)", aspectmode="data"),
        updatemenus=[dict(type="buttons", buttons=[dict(label="▶ Play θ", method="animate", args=[None, {"frame": {"duration": 300, "redraw": True}, "fromcurrent": True}])])],
        sliders=[dict(steps=[dict(method="animate", args=[[str(i)], {"mode": "immediate", "frame": {"duration": 0, "redraw": True}}], label=f"{th:.2f}") for i, th in enumerate(theta)], currentvalue={"prefix": "θ = "})]
    )
    fig.show()


def dark_dashboard(native, null, top_ablation, random_ablation, trajectories, random_gap_samples):
    fig, ax = plt.subplots(2, 2, figsize=(15, 11), facecolor="#111111")
    for a in ax.ravel():
        a.set_facecolor("#111111")
        a.tick_params(colors="white")
        for spine in a.spines.values():
            spine.set_color("white")
        a.xaxis.label.set_color("white")
        a.yaxis.label.set_color("white")
        a.title.set_color("white")

    # A: susceptibility landscape
    th = native["theta"]
    ax[0, 0].plot(th, native["susceptibility"], marker="o", label="Native")
    ax[0, 0].plot(th, null["susceptibility"], marker="o", label="Maslov–Sneppen null")
    ax[0, 0].plot(th, top_ablation["susceptibility"], linestyle="--", label="Persistent top-leverage ablation")
    ax[0, 0].plot(th, random_ablation["susceptibility"], linestyle="--", label="Random matched ablation")
    ax[0, 0].set_title("Synthetic-dimension susceptibility")
    ax[0, 0].set_xlabel("θ")
    ax[0, 0].set_ylabel("Σe Le")
    ax[0, 0].legend(frameon=False, labelcolor="white")
    ax[0, 0].grid(alpha=0.15)

    # B: subspace transport
    ax[0, 1].plot(th, native["subspace_transport"], marker="o", label="Native")
    ax[0, 1].plot(th, null["subspace_transport"], marker="o", label="Null")
    ax[0, 1].set_title("Soft-mode subspace transport")
    ax[0, 1].set_xlabel("θ")
    ax[0, 1].set_ylabel(r"$||P_K(θ+Δθ)-P_K(θ)||_F$")
    ax[0, 1].legend(frameon=False, labelcolor="white")
    ax[0, 1].grid(alpha=0.15)

    # C: ablation gap response
    native_gap = native["gap"]
    top_gap = top_ablation["gap"]
    rand_gap = random_ablation["gap"]
    ax[1, 0].plot(th, top_gap - native_gap, marker="o", label="Top leverage")
    ax[1, 0].plot(th, rand_gap - native_gap, marker="o", label="Random matched")
    ax[1, 0].axhline(0.0, linewidth=1)
    ax[1, 0].set_title("θ-resolved lowest-mode intervention")
    ax[1, 0].set_xlabel("θ")
    ax[1, 0].set_ylabel(r"$Δλ_{min}^{+}(θ)$")
    ax[1, 0].legend(frameon=False, labelcolor="white")
    ax[1, 0].grid(alpha=0.15)

    # D: quantum yield
    for name, (t, Y) in trajectories.items():
        ax[1, 1].plot(t, Y, linewidth=2, label=name)
    ax[1, 1].set_title("Lindblad singlet fraction")
    ax[1, 1].set_xlabel("Time (μs)")
    ax[1, 1].set_ylabel("Y_S(t)")
    ax[1, 1].set_ylim(-0.02, 1.02)
    ax[1, 1].legend(frameon=False, labelcolor="white")
    ax[1, 1].grid(alpha=0.15)

    fig.suptitle("TQS v9.1 — Synthetic-Dimensional Spectral Geometry", color="white", fontsize=16)
    plt.tight_layout()
    plt.show()

    plt.figure(figsize=(8, 5), facecolor="#111111")
    ax2 = plt.gca()
    ax2.set_facecolor("#111111")
    ax2.hist(random_gap_samples, bins=12, alpha=0.85, label="Random ablation null")
    ax2.set_title("Random-ablation null distribution", color="white")
    ax2.set_xlabel("Mean Δλmin+ across θ", color="white")
    ax2.set_ylabel("Count", color="white")
    ax2.tick_params(colors="white")
    for spine in ax2.spines.values():
        spine.set_color("white")
    ax2.grid(alpha=0.15)
    plt.tight_layout()
    plt.show()


def main() -> None:
    cfg = CFG
    rng = np.random.default_rng(cfg.seed)

    print("=" * 82)
    print("TQS v9.1 — SYNTHETIC-DIMENSION SPECTRAL GEOMETRY")
    print("=" * 82)
    print("No internet/PDB dependency. Synthetic Cα scaffold.\n")

    coords = generate_3d_fold(cfg)
    edges = build_contact_graph(coords, cfg.cutoff_A)
    print(f"Native scaffold: N={len(coords)}, E={len(edges)}")

    null_edges = maslov_sneppen(edges, cfg.N, cfg, rng)
    assert np.array_equal(degree_sequence(edges, cfg.N), degree_sequence(null_edges, cfg.N))
    print("Maslov–Sneppen degree sequence invariant: TRUE")

    print("\n[1/6] Native θ sweep...")
    native = theta_sweep(coords, edges, cfg)
    print("[2/6] Null θ sweep...")
    null = theta_sweep(coords, null_edges, cfg)

    # Persistent-control intervention is based on mean leverage over the entire cycle.
    top_idx = select_persistent_edges(native["leverage_maps"], cfg.ablation_fraction)
    top_edges = remove_edges(edges, top_idx)
    print("[3/6] Persistent top-leverage ablation θ sweep...")
    top_ablation = theta_sweep(coords, top_edges, cfg)

    random_idx = rng.choice(len(edges), size=len(top_idx), replace=False)
    random_edges = remove_edges(edges, random_idx)
    print("[4/6] Random matched ablation θ sweep...")
    random_ablation = theta_sweep(coords, random_edges, cfg)

    print("[5/6] Random ablation null ensemble...")
    random_gap_samples = random_ablation_theta_ensemble(
        coords, edges, cfg.ablation_fraction, cfg.random_ablation_runs, rng, cfg
    )

    native_gap = native["gap"]
    top_shift = float(np.mean(top_ablation["gap"] - native_gap))
    random_shift_q = np.quantile(random_gap_samples, [0.025, 0.50, 0.975])
    outside95 = bool(top_shift < random_shift_q[0] or top_shift > random_shift_q[2])
    p_emp = float((1 + np.count_nonzero(np.abs(random_gap_samples) >= abs(top_shift))) / (len(random_gap_samples) + 1))

    print("\n[6/6] Lindblad closure...")
    Hs, PS, jumps = build_spin_model(cfg)

    # Explicitly mark this as a phenomenological bridge.
    scores = {
        "Native": normalized_cycle_score(native, native),
        "Maslov–Sneppen null": normalized_cycle_score(null, native),
        "Persistent top-leverage ablation": normalized_cycle_score(top_ablation, native),
        "Random matched ablation": normalized_cycle_score(random_ablation, native),
    }

    trajectories = {}
    for label, score in scores.items():
        gamma = score_to_gamma(score, cfg)
        t, Y = integrate_lindblad(gamma, Hs, PS, jumps, cfg)
        trajectories[label] = (t, Y)
        print(f"{label:30s} score={score:.6f} gamma={gamma:.6f} μs^-1 YS(5μs)={Y[-1]:.6f}")

    native_gap_stats = {
        "min": float(np.min(native["gap"])),
        "max": float(np.max(native["gap"])),
        "cv": float(np.std(native["gap"]) / max(np.mean(native["gap"]), 1e-14)),
    }

    native_persistence = native["leverage_persistence"]
    strongest = np.argsort(native_persistence)[::-1][:10]

    print("\n--- SYNTHETIC-CYCLE DIAGNOSTICS ---")
    print(f"Native min positive gap: {native_gap_stats['min']:.6e}")
    print(f"Native max positive gap: {native_gap_stats['max']:.6e}")
    print(f"Native gap CV:           {native_gap_stats['cv']:.6f}")
    print(f"Persistent-control mean membership (top edge): {native_persistence[strongest[0]]:.3f}")
    print(f"Persistent-control mean membership (top 10):   {native_persistence[strongest].mean():.3f}")
    print(f"Mean top-ablation Δλmin+: {top_shift:.6e}")
    print(f"Random null 95% interval: [{random_shift_q[0]:.6e}, {random_shift_q[2]:.6e}]")
    print(f"Outside 95% random boundary: {outside95}")
    print(f"Empirical two-sided p: {p_emp:.4f}")
    print(f"Mean native subspace transport: {np.mean(native['subspace_transport']):.6e}")
    print(f"Mean null subspace transport:   {np.mean(null['subspace_transport']):.6e}")
    print(f"Mean native leverage Gini: {np.mean(native['leverage_gini']):.6f}")
    print(f"Mean null leverage Gini:   {np.mean(null['leverage_gini']):.6f}")
    print(f"Mean native leverage IPR:  {np.mean(native['leverage_ipr']):.6e}")
    print(f"Mean null leverage IPR:    {np.mean(null['leverage_ipr']):.6e}")

    print("\n--- EPISTEMIC LOCKS ---")
    print("1) θ is one synthetic cyclic parameter; this does NOT establish a 4D second Chern number.")
    print("2) Gap persistence is not by itself proof of topological protection.")
    print("3) γ_eff(score) is a phenomenological closure, not a calibrated microscopic radical-pair rate law.")
    print("4) The null is topology-only; it is not a physically realistic alternative protein conformation.")

    if cfg.render_3d:
        print("\nRendering 3D native leverage map...")
        make_3d_leverage_plot(coords, edges, native["leverage_maps"][0], "TQS v9.1 — 3D native spectral-control map")

        print("Rendering 3D θ animation...")
        make_theta_animation(coords, edges, native["theta"], native["leverage_maps"])

    dark_dashboard(native, null, top_ablation, random_ablation, trajectories, random_gap_samples)


if __name__ == "__main__":
    main()