# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nj7Cen-VLdb-s9TKVZ3HgWhaz6Akh8pe
"""

# ============================================================
# TOPological Spectral Homeostasis v5.1
# 3D ENM VISUALIZATION + EIGENMODE ANIMATION
# GOOGLE COLAB
# ============================================================

import os
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import eigh
import networkx as nx

# Plotly cho mô phỏng 3D tương tác
import plotly.graph_objects as go
from google.colab import files


# ============================================================
# 1. UPLOAD PDB
# ============================================================

TARGET_FILE = "1U3C.pdb"
CONTROL_FILE = "1U7C.pdb"

missing = [
    f for f in [TARGET_FILE, CONTROL_FILE]
    if not os.path.isfile(f)
]

if missing:
    print("Upload các file:")
    for f in missing:
        print("   ", f)

    uploaded = files.upload()

    for required in [TARGET_FILE, CONTROL_FILE]:
        if not os.path.isfile(required):
            raise FileNotFoundError(
                f"Không tìm thấy {required}. "
                "Tên file phải chính xác."
            )


# ============================================================
# 2. LOAD C-alpha COORDINATES
# ============================================================

def load_ca_coords(pdbfile):
    coords = []
    residue_ids = []

    with open(
        pdbfile,
        "r",
        encoding="utf-8",
        errors="ignore"
    ) as f:

        for line in f:

            if not line.startswith("ATOM"):
                continue

            if line[12:16].strip() != "CA":
                continue

            try:
                x = float(line[30:38])
                y = float(line[38:46])
                z = float(line[46:54])
            except ValueError:
                continue

            resid = line[22:26].strip()

            coords.append([x, y, z])
            residue_ids.append(resid)

    coords = np.asarray(coords, dtype=float)

    if len(coords) == 0:
        raise ValueError(
            f"Không tìm thấy C-alpha trong {pdbfile}"
        )

    return coords, residue_ids


coords_target, resid_target = load_ca_coords(TARGET_FILE)
coords_control, resid_control = load_ca_coords(CONTROL_FILE)

print("TARGET :", coords_target.shape)
print("CONTROL:", coords_control.shape)


# ============================================================
# 3. BUILD CONTACT NETWORK
# ============================================================

CUTOFF_A = 7.0


def build_contact_graph(coords, cutoff=7.0):
    G = nx.Graph()

    N = len(coords)
    G.add_nodes_from(range(N))

    for i in range(N):
        for j in range(i + 1, N):

            d = np.linalg.norm(
                coords[j] - coords[i]
            )

            if 0.0 < d <= cutoff:
                G.add_edge(i, j)

    return G


G_target = build_contact_graph(
    coords_target,
    CUTOFF_A
)

G_control = build_contact_graph(
    coords_control,
    CUTOFF_A
)

print("\nCONTACT NETWORK")
print(
    f"Target : N={G_target.number_of_nodes()}, "
    f"E={G_target.number_of_edges()}"
)

print(
    f"Control: N={G_control.number_of_nodes()}, "
    f"E={G_control.number_of_edges()}"
)


# ============================================================
# 4. 3N x 3N ENM HESSIAN
# ============================================================

def build_hessian(coords, cutoff=7.0):
    N = len(coords)
    H = np.zeros((3*N, 3*N), dtype=float)

    for i in range(N):

        for j in range(i + 1, N):

            diff = coords[j] - coords[i]
            dist = np.linalg.norm(diff)

            if dist == 0.0 or dist > cutoff:
                continue

            u = diff / dist
            block = np.outer(u, u)

            ii = slice(3*i, 3*i+3)
            jj = slice(3*j, 3*j+3)

            H[ii, jj] -= block
            H[jj, ii] -= block

            H[ii, ii] += block
            H[jj, jj] += block

    H = 0.5 * (H + H.T)

    return H


H_target = build_hessian(
    coords_target,
    CUTOFF_A
)


# ============================================================
# 5. EIGEN-DECOMPOSITION
# ============================================================

print("\nĐang tính eigenmodes Target...")

evals, evecs = eigh(H_target)

evals = np.real(evals)

# Sai số số học
evals[evals < 0] = 0.0

max_eval = max(
    np.max(evals),
    1.0
)

tol = 1e-8 * max_eval

positive_mask = evals > tol

positive_evals = evals[positive_mask]
positive_vecs = evecs[:, positive_mask]

omega = np.sqrt(
    positive_evals
)

print(
    f"Positive modes: {len(omega)} / {len(evals)}"
)

print(
    f"Lowest positive omega = {omega[0]:.6g}"
)


# ============================================================
# 6. CHỌN EIGENMODE ĐỂ MÔ PHỎNG
# ============================================================

# Mode thấp nhất không-zero
MODE_INDEX = 0

mode_vector = positive_vecs[:, MODE_INDEX]

mode_vector = mode_vector.reshape(
    (-1, 3)
)

# Chuẩn hóa mode
norm = np.max(
    np.linalg.norm(
        mode_vector,
        axis=1
    )
)

if norm == 0:
    raise ValueError(
        "Eigenmode có độ lớn bằng 0."
    )

mode_vector = mode_vector / norm


# ============================================================
# 7. DEGREE-PRESERVING MASLOV-SNEPPEN
# ============================================================

def randomize_graph_degree_preserving(
    G,
    swaps_factor=5,
    seed=42
):

    rng = np.random.default_rng(seed)

    R = G.copy()

    target_swaps = (
        swaps_factor *
        R.number_of_edges()
    )

    edges = list(R.edges())

    accepted = 0
    attempts = 0
    max_attempts = max(
        1000,
        50 * target_swaps
    )

    while (
        accepted < target_swaps
        and attempts < max_attempts
    ):

        attempts += 1

        if len(edges) < 2:
            break

        a, b = edges[
            rng.integers(len(edges))
        ]

        c, d = edges[
            rng.integers(len(edges))
        ]

        if len(
            {a, b, c, d}
        ) < 4:
            continue

        # Hai cách nối chéo
        choices = [
            (a, d, c, b),
            (a, c, d, b)
        ]

        new_edges = choices[
            rng.integers(2)
        ]

        e1 = (
            new_edges[0],
            new_edges[1]
        )

        e2 = (
            new_edges[2],
            new_edges[3]
        )

        if e1[0] == e1[1]:
            continue

        if e2[0] == e2[1]:
            continue

        if R.has_edge(*e1):
            continue

        if R.has_edge(*e2):
            continue

        R.remove_edge(a, b)
        R.remove_edge(c, d)

        R.add_edge(*e1)
        R.add_edge(*e2)

        accepted += 1

        edges = list(R.edges())

    return R, accepted


G_random, accepted = (
    randomize_graph_degree_preserving(
        G_target,
        swaps_factor=5,
        seed=42
    )
)

degree_exact = all(
    G_target.degree(i)
    == G_random.degree(i)
    for i in G_target.nodes()
)

print("\nMASLOV-SNEPPEN")
print("Accepted swaps:", accepted)
print("Degree sequence exact:", degree_exact)


# ============================================================
# 8. EDGE TRACES CHO PLOTLY
# ============================================================

def edge_trace(
    coords,
    G,
    width=2
):

    x = []
    y = []
    z = []

    for i, j in G.edges():

        x.extend([
            coords[i, 0],
            coords[j, 0],
            None
        ])

        y.extend([
            coords[i, 1],
            coords[j, 1],
            None
        ])

        z.extend([
            coords[i, 2],
            coords[j, 2],
            None
        ])

    return go.Scatter3d(
        x=x,
        y=y,
        z=z,
        mode="lines",
        line=dict(
            width=width
        ),
        hoverinfo="skip",
        name="ENM contacts"
    )


def node_trace(coords):

    N = len(coords)

    return go.Scatter3d(
        x=coords[:, 0],
        y=coords[:, 1],
        z=coords[:, 2],
        mode="markers",
        marker=dict(
            size=4
        ),
        text=[
            f"Residue {i+1}"
            for i in range(N)
        ],
        hovertemplate="%{text}<extra></extra>",
        name="Cα"
    )


# ============================================================
# 9. STATIC 3D NATIVE STRUCTURE
# ============================================================

fig_native = go.Figure()

fig_native.add_trace(
    edge_trace(
        coords_target,
        G_target
    )
)

fig_native.add_trace(
    node_trace(
        coords_target
    )
)

fig_native.update_layout(
    title=(
        "1U3C — 3D Cα Elastic Network "
        f"(cutoff = {CUTOFF_A:.1f} Å)"
    ),
    scene=dict(
        xaxis_title="X (Å)",
        yaxis_title="Y (Å)",
        zaxis_title="Z (Å)",
        aspectmode="data"
    ),
    width=950,
    height=750
)

fig_native.show()


# ============================================================
# 10. 3D RANDOMIZED TOPOLOGY
# ============================================================

fig_random = go.Figure()

fig_random.add_trace(
    edge_trace(
        coords_target,
        G_random
    )
)

fig_random.add_trace(
    node_trace(
        coords_target
    )
)

fig_random.update_layout(
    title=(
        "1U3C — Degree-Preserving Randomized ENM"
    ),
    scene=dict(
        xaxis_title="X (Å)",
        yaxis_title="Y (Å)",
        zaxis_title="Z (Å)",
        aspectmode="data"
    ),
    width=950,
    height=750
)

fig_random.show()


# ============================================================
# 11. EIGENMODE ANIMATION
# ============================================================

N = len(coords_target)

# Biên độ biến dạng để hiển thị
AMPLITUDE_A = 4.0

N_FRAMES = 40

phases = np.linspace(
    0,
    2*np.pi,
    N_FRAMES,
    endpoint=False
)

frames = []

for phase in phases:

    displacement = (
        AMPLITUDE_A *
        np.sin(phase) *
        mode_vector
    )

    displaced = (
        coords_target +
        displacement
    )

    node = go.Scatter3d(
        x=displaced[:, 0],
        y=displaced[:, 1],
        z=displaced[:, 2],
        mode="markers",
        marker=dict(
            size=5
        ),
        text=[
            f"Residue {i+1}"
            for i in range(N)
        ],
        name="Cα"
    )

    # ENM native edges di chuyển cùng node
    edge = edge_trace(
        displaced,
        G_target,
        width=2
    )

    frames.append(
        go.Frame(
            data=[edge, node],
            name=f"{phase:.4f}"
        )
    )


# ============================================================
# 12. FIGURE ANIMATION
# ============================================================

initial_displacement = (
    AMPLITUDE_A *
    np.sin(phases[0]) *
    mode_vector
)

initial_coords = (
    coords_target +
    initial_displacement
)

fig_mode = go.Figure(
    data=[
        edge_trace(
            initial_coords,
            G_target
        ),
        node_trace(
            initial_coords
        )
    ],
    frames=frames
)

fig_mode.update_layout(
    title=(
        "1U3C — 3D ENM Eigenmode Animation "
        f"| mode = {MODE_INDEX + 1}, "
        f"ω = {omega[MODE_INDEX]:.5g}"
    ),
    scene=dict(
        xaxis_title="X (Å)",
        yaxis_title="Y (Å)",
        zaxis_title="Z (Å)",
        aspectmode="data"
    ),
    width=1000,
    height=800,
    updatemenus=[
        dict(
            type="buttons",
            showactive=False,
            x=0.05,
            y=1.05,
            buttons=[
                dict(
                    label="▶ Play",
                    method="animate",
                    args=[
                        None,
                        dict(
                            frame=dict(
                                duration=80,
                                redraw=True
                            ),
                            transition=dict(
                                duration=0
                            ),
                            fromcurrent=True
                        )
                    ]
                ),
                dict(
                    label="⏸ Pause",
                    method="animate",
                    args=[
                        [None],
                        dict(
                            frame=dict(
                                duration=0,
                                redraw=False
                            ),
                            mode="immediate"
                        )
                    ]
                )
            ]
        )
    ]
)

fig_mode.show()


# ============================================================
# 13. MODE INFORMATION
# ============================================================

print("\n" + "="*70)
print("3D ENM SUMMARY")
print("="*70)

print(
    f"Protein residues       : {N}"
)

print(
    f"ENM cutoff             : {CUTOFF_A:.2f} Å"
)

print(
    f"Native contacts        : "
    f"{G_target.number_of_edges()}"
)

print(
    f"Randomized contacts    : "
    f"{G_random.number_of_edges()}"
)

print(
    f"Degree preserved       : "
    f"{degree_exact}"
)

print(
    f"Displayed mode         : "
    f"{MODE_INDEX + 1}"
)

print(
    f"Eigenvalue λ           : "
    f"{positive_evals[MODE_INDEX]:.8g}"
)

print(
    f"Pseudo-frequency ω     : "
    f"{omega[MODE_INDEX]:.8g}"
)

print(
    f"Visualization amplitude: "
    f"{AMPLITUDE_A:.2f} Å"
)

print("="*70)
